### ISSUE TITLE
Compatibility bug for The One Probe

### ISSUE THREAD

**Issue by mcBegins2Snow** [TeamMetallurgy/Atum2#103]
**Mods and Forge list**

1. Atum-1.12.2-2.0.6
2. theoneprobe-1.12-1.4.27
3. forge-1.12.2-14.23.5.2838

When installed Atum mod, The One Probe shows all blocks are error information. Entity information doesn't have problem.
![2019-05-17_16 29 07](https://user-images.githubusercontent.com/37864486/57914625-92e4cc00-78c1-11e9-9281-fd84dd8d90b4.png)
`Error: theoneprobe:default`
`Error: atum`

Without Atum, The One Probe doesn't have any problem.

**Comment by GirafiStudios** [comment]
Please update to The One Probe version 1.4.28
