### ISSUE TITLE
Z Fighting still ocurring for some things

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/Atum2#109]
Wolf armor is fixed, but now it seems the saddle is fighting with the armor, so it shimmers in and out of the armor.
Camels saddles appear to be fine, but the armor and carpet are conflicting with eachother.
![2019-05-18_19 07 44](https://user-images.githubusercontent.com/50718369/57975870-b6327880-79a0-11e9-98b9-410ae743993c.png)
![2019-05-18_19 03 06](https://user-images.githubusercontent.com/50718369/57975871-bd598680-79a0-11e9-9c58-b8ca9efae969.png)
![2019-05-18_19 09 15](https://user-images.githubusercontent.com/50718369/57975872-c77b8500-79a0-11e9-9048-9dfc37043607.png)

**Comment by lclc98** [comment]
From what I can see, the released isn't released, but this should be kept open until it is, and you can test it again. (I will poke Girafi about this right now)

**Comment by GirafiStudios** [comment]
Will be fixed in Atum version 2.0.7.
Will be out later today, if I get a response from https://github.com/TeamMetallurgy/Atum2/issues/94
Otherwise it'll be out tomorrow.

**Comment by Azuriuz** [comment]
Sorry, the server had just been updated so I thought it was on the newest Atum version ^-^;;
