### ISSUE TITLE
Missing "Show Recipes" button on the Kiln's GUI

### ISSUE THREAD

**Issue by mcBegins2Snow** [TeamMetallurgy/Atum2#111]
Atum version: 2.0.6
It's inconvenient for players to look up Kiln's JEI recipes. I think it's better to add this button. Just like vanilla furnace.

**Comment by GirafiStudios** [comment]
![i1hzwEe](https://user-images.githubusercontent.com/6305377/57987025-5a3d2200-7a7c-11e9-8a6d-c9bfaa9974d0.png)
Thank you for your suggestion!
First of all, I do not see anything different about how Furnace recipes are showed.
If you want a list of all Kiln recipes, you can just click on where it says "Kiln" at the top, as shown on the picture.
