### ISSUE TITLE
Issue - Changing ID is ignored in actual mod but not config.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TeamMetallurgy/Atum2#112]
This is a really late report that does affect 2.0.6 release and has been an issue for a long time.

**Comment by GirafiStudios** [comment]
Thank you for your report!
Please describe in more detail what exactly the issue is.

**Comment by P3rf3ctXZer0** [comment]
If you change the id in the config from 17 the mod still tries to use 17 and even though the log says the dimensional id is changed the mod is still trying to force 17

**Comment by P3rf3ctXZer0** [comment]
In order to trigger bug you need to use the first 200 ids. then try and change the mod to use dimid like 201

**Comment by GirafiStudios** [comment]
Atum will never support any mods that extend the amount of IDs.
This does seem to be a problem with only Atum though, so I'll look into it.

**Comment by P3rf3ctXZer0** [comment]
Being stubborn on a stance is foolish. Even ftb now uses JEID I mean it is your mod but if you want people to use it - might be a good idea to stay with the crowd a bit. At any rate I just won't use the mod there are plenty of mods out there. Thanks for your time.

**Comment by GirafiStudios** [comment]
Just Enough IDs does not provide a way to add support for it specifically, so it would have to be done on their side (Or the addon you mentioned)

**Comment by GirafiStudios** [comment]
I can only reproduce this when you try to load an old world after changing the ID.
What use case do you have for changing the ID of a dimension, in a world you already started playing on?

**Comment by Shadowclaimer** [comment]
I have blocked P3rf3ctXZer0 from submitting the git.

I won't stand for rudeness in the github issues.
