### ISSUE TITLE
Maps on item frames on crates makes them invisible

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/Atum2#113]
lol this is silly to look at; can check out the bug on the current mod test server (but no mods are used in this so pretty sure it's an atum bug)

**Comment by Azuriuz** [comment]
![2019-05-19_16 02 51](https://user-images.githubusercontent.com/50718369/57987526-7d51dc80-7a50-11e9-8402-6a6fc74c4232.png)

**Comment by Shadowclaimer** [comment]
This might be a Quark issue, can you test this in a new instance with just vanilla item frames and Atum?

**Comment by GirafiStudios** [comment]
Cannot reproduce.
![8atuMJS](https://user-images.githubusercontent.com/6305377/57987643-a7bd8d00-7a84-11e9-9791-c9b634643f3e.png)
Could you try the latest Jenkins build, and see if you can get it to happen there?

**Comment by GirafiStudios** [comment]
Turned out to be an issue in Quark.
I made a PR for Quark that fixes it here: https://github.com/Vazkii/Quark/pull/1269
