### ISSUE TITLE
Server crash when using Atum 2.0.7 with Champions 1.0.9

### ISSUE THREAD

**Issue by ArkenorOakshadow** [TeamMetallurgy/Atum2#114]
[2019-05-20-6.log](https://github.com/TeamMetallurgy/Atum2/files/3199652/2019-05-20-6.log)

Removing Champions prevented the crash. This did not affect my client machine, only the server.

**Comment by GirafiStudios** [comment]
Thank you for your report!
What version of Forge are you using?

**Comment by ArkenorOakshadow** [comment]
2836

**Comment by GirafiStudios** [comment]
Good catch!
Will probably be a little bit before it makes it to a CurseForge release, but you can grab the latest version form Jenkins here: http://girafi.dk/jenkins/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%20Jenkins/

**Comment by ArkenorOakshadow** [comment]
Happy to help! Thanks for fixing it so quickly!
