### ISSUE TITLE
The pyramid's blocks can be destroyed when touched by Wither boss

### ISSUE THREAD

**Issue by mcBegins2Snow** [TeamMetallurgy/Atum2#125]
mod version: 2.0.8
The pyramid's blocks cannot be mined by player, but Wither boss can. It makes player allow to enter the lowest room directly to challenge Pharaoh boss.

**Comment by Shadowclaimer** [comment]
If a player summons a Wither just to sneak to a Pharaoh I think they've earned it honestly. The Wither is a bigger challenge than the rest of the pyramid.
