### ISSUE TITLE
Stoneguard Weapons Can't Be Repaired

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/Atum2#126]
![2019-06-02_01 26 03](https://user-images.githubusercontent.com/50718369/58757177-912c2280-84d5-11e9-8630-adc2a9860dad.png)
![2019-06-02_01 26 08](https://user-images.githubusercontent.com/50718369/58757178-912c2280-84d5-11e9-8f5c-cc0ca7455740.png)
![2019-06-02_01 26 13](https://user-images.githubusercontent.com/50718369/58757179-912c2280-84d5-11e9-97f4-1799e816fd9b.png)
![2019-06-02_01 26 17](https://user-images.githubusercontent.com/50718369/58757180-91c4b900-84d5-11e9-8abd-b9fec7d959b4.png)
![2019-06-02_01 26 22](https://user-images.githubusercontent.com/50718369/58757181-91c4b900-84d5-11e9-92f5-84e1ddf0aab8.png)

**Comment by Azuriuz** [comment]
They can be combined, just not repaired in an anvil.

**Comment by GirafiStudios** [comment]
Thank you for the report!
Will be fixed in next version on CurseForge.
