### ISSUE TITLE
Stoneguards can't pathfind through the limestone doors in pyramids

### ISSUE THREAD

**Issue by TopPercentageRattata** [TeamMetallurgy/Atum2#129]
Stoneguard mobs are unable to pathfind through the limestone doors found in pyramids, single or double, and possibly more doors.

**Comment by GirafiStudios** [comment]
That is intended. Stoneguards are not smart enough to open doors.

**Comment by TopPercentageRattata** [comment]
Oh sorry I guess I wasn't clear, I meant you can open the doors and a stone guard can be in the room and it pathfinders right to the door where you can hit it through the open door but it cant pass through for some reason

**Comment by GirafiStudios** [comment]
Oh I misunderstood then.
I'll take a look at it, but it's most likely just because of vanilla mobs having issues with doors in 1.12

**Comment by GirafiStudios** [comment]
Seems to be a vanilla issue. Zombies etc. can't walk through any open doors either.
