### ISSUE TITLE
Alpha wolves eating items off ground doesn't heal

### ISSUE THREAD

**Issue by TopPercentageRattata** [TeamMetallurgy/Atum2#130]
Alpha wolves eating food off ground doesn't heal them, just puts them in mating mode, at least if riding them. Normally when hand feeding mating mote hearts only can appear if full hp first.

**Comment by GirafiStudios** [comment]
Could you try rephrasing the issue? I have no idea what you're trying to say.

**Comment by TopPercentageRattata** [comment]
Sorry. So desert and dire desert wolves can be right clicked with food to heal them like vanilla wolves, but they can also eat food off of ground. Normally when wolves get right clicked with food, first it heals them, and they can only enter mating mode(hearts) when full hp. Eating food off of ground just seems to put them in mating mode, and doesn't heal them so it doesn't behave like normal right clicking of food. Makes you have to hop off of dire desert wolf to right click and heal them and then chase them down to get back on.

**Comment by GirafiStudios** [comment]
I assume you by Dire Desert Wolfs mean Alpha Desert Wolfs?
Vanilla does not allow for eating food off the ground. There might be a mod that allows you to do that, but I can't test it, if you don't let me know what mod you're using for that.

**Comment by TopPercentageRattata** [comment]
Oh sorry, assumed it was a feature for desert wolves, turns out it was a quark feature where animals eat breeding foods off of ground for automation. Bug with other mod

**Comment by GirafiStudios** [comment]
Alright, I'll look into if there is anything I can do about that on our side.

**Comment by GirafiStudios** [comment]
The Quark feature does not allow for healing with the eating off the ground - only breeding.
