### ISSUE TITLE
Fishing in Atum gives no exp

### ISSUE THREAD

**Issue by TopPercentageRattata** [TeamMetallurgy/Atum2#131]
Fishing with either vanilla fishing rod or Atum's Bounty in the atum dimension, no matter which of the 4 fish you fish up, no exp is given.

**Comment by GirafiStudios** [comment]
Thank you for your suggestion.
I've added so Atum's Bounty will give you some exp.
If a normal fishing rod in Atum would give you exp, that would be a very easy way to get some decent gear with enchants.
