### ISSUE TITLE
Possible Incompatibility with Advanced Rocketry

### ISSUE THREAD

**Issue by nrllewellyn** [TeamMetallurgy/Atum2#134]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2838
Atum Version: 2.0.9
Advanced Rocketry Version: 1.5.0-139

Description:
Game crashes when entering the Atum Dimension due to a ClassCastException on the world provider.

Crash Log:
https://pastebin.com/Rus1b02c

**Comment by nrllewellyn** [comment]
Note: This can be worked around by setting Advanced Rocketry's `planet.minDimension` to a value larger than Atum's dimension ID

**Comment by GirafiStudios** [comment]
Thank you for your report!
How exactly do you reproduce this crash?

**Comment by nrllewellyn** [comment]
I believe it's just "try to go to Atum while Advanced Rocketry is installed". Otherwise, it may be a combination of the mods I'm using. (I can try to narrow it down in a couple of days if just installing Advanced Rocketry doesn't reproduce it.)

**Comment by GirafiStudios** [comment]
I tried that plenty of times. Also tried installing Advanced Rocketry first, going to planet 17 (Same ID as Atum), and then installing Atum. Still didn't cause it to crash.
You could try this build, and see if it fixes it for you? https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%20Jenkins/64/

**Comment by nrllewellyn** [comment]
Crazy busy at the moment, but give me a couple of days and I'll give it a shot! :-)

**Comment by GirafiStudios** [comment]
@nrllewellyn friendly reminder that it've been a couple of days :)

**Comment by nrllewellyn** [comment]
Sorry for the delay! I've tried a few different ways to reproduce the issue, with no luck, so either you fixed it or there was something odd about my configs. :-)
