### ISSUE TITLE
Impossibility to use Wool since Atum installed

### ISSUE THREAD

**Issue by phiphila** [TeamMetallurgy/Atum2#135]
in fact, the recipe does not available, just atum:linen is visible into JEI, so I cannot use wool again for my creates. and I do not know how add the wool in dictionary for use again. help me please.

P.S: I use Atum-1.12.2-2.0.9 version

**Comment by GirafiStudios** [comment]
Please try to explain it in another way, I'm not quite sure what you're trying to say.

**Comment by phiphila** [comment]
Before atum mod was installed, i could make wools colorful , with a wool block of a sheep and a colorant, now since Atum mod is installed, I cannot make it again, now the recipe of the wools colorful are not available, now for making a wool colorful, it is necessary to use atum:linen and a colorant for make the same than previously, how to make anew a wool colorful block with a wool of sheep and not just with atum:linen ? thanks
And sorry for my poor english level :(

**Comment by GirafiStudios** [comment]
You're good, I just wanted to make sure I understood the issue correctly.
What version of Forge are you using?
Updating to Minecraft Forge version 14.23.5.2836 or newer should fix your issue

**Comment by GirafiStudios** [comment]
Found a fix for it, will be in next Atum release :)
