### ISSUE TITLE
Unable to open sarcophagus if the player leaves/dies during the battle then comes back to kill the pharaoh

### ISSUE THREAD

**Issue by al132mc** [TeamMetallurgy/Atum2#137]
> 
> After talking to PeachizXD more, it seems like summoning the pharaoh, then leaving Atum and coming back, then killing the pharaoh causes the issue.
> 
> 
> They had died before getting the pharaoh kill. Not sure if they /home back or used some other way.
> 

You can see [this issue](https://github.com/al132mc/antimatter-chemistry/issues/57) for more information. Let me know if you have any more questions.

**Comment by GirafiStudios** [comment]
Thank you for the report!
I've been trying to reproduce this quite a bit. Tried teleporting around, switching dimension, dying etc., but it have worked just fine for me every time.
I would need you to provide a consistent way to reproduce the issue, or a world (With as few mods as possible), with you standing in front of the sarcophagus that cannot be opened :)

**Comment by Next-victim** [comment]
An additional note of info: a creative mode player can break it and have the items drop.

See: https://github.com/al132mc/antimatter-chemistry/issues/57#issuecomment-503382048

**Comment by Muphet** [comment]
happened to me just now, can confirm

**Comment by GirafiStudios** [comment]
Please provide a world where it's happening with coordinates to the pyramid.

**Comment by Meldexun** [comment]
I have the same issue. It always occurs once the chunk of the pharaoh and his sarcophagus is unloaded.
So to reproduce:

    You summon a pharaoh
    Exit the world to the main menu (chunks get unloaded)
    Rejoin the world
    Kill the pharaoh
    Sarcophagus is bugged and can't be opened

**Comment by GirafiStudios** [comment]
Thanks for giving some more insight!
If you could provide a world where it happens that would be great, because I can't reproduce it with those steps.

**Comment by Meldexun** [comment]
So i installed Atum 2 and Optifine.
Then i created a normal world with the seed: 3916825317961709452
Then i built a portal and searched for the nearest Pyramid. Sacrophagus room at 90 57 320
I placed the Royal Torches and right clicked the sacrophagus.
I clicked "Save and Quit to Title".
I rejoined the world and killed the Pharaoh.

That is the world with 3 torches placed at the sacrophag.
[TestWorld.zip](https://github.com/TeamMetallurgy/Atum2/files/3550579/TestWorld.zip)

**Comment by GirafiStudios** [comment]
Thanks a lot for the test world @Meldexun, I would not have been able to fix the issue with it - as I can still not recreate the issue following the exact same steps in a new world.
The fix will unfortunately not fix the issue for Sarcophagi that have already been affected, but it'll fix new ones.
