### ISSUE TITLE
Invisible Camel

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/Atum2#139]
I have no idea how this happened. I went to pull off it's diamond armor to show the camel off and it was invisible. Not sure if it was invis to begin with and I noticed when I pulled the armor off, or if I triggered it by removing the armor. 

![2019-06-18_01 27 29](https://user-images.githubusercontent.com/50718369/59655493-87a6e980-9168-11e9-9bc8-9193ddbed915.png)
![2019-06-18_01 27 57](https://user-images.githubusercontent.com/50718369/59655494-87a6e980-9168-11e9-8942-e6b301ed30e5.png)

**Comment by lclc98** [comment]
Sorry this was a mistake on my part, custom names causes the texture to break unless it was Girafi.

**Comment by Azuriuz** [comment]
oh yep, it was a named camel
