### ISSUE TITLE
Spawners Not Spawning?

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/Atum2#140]
![2019-06-23_05 59 10](https://user-images.githubusercontent.com/50718369/59974631-89174e00-957c-11e9-8287-d25aac0baad6.png)

I'd noticed it seemed like sometimes spawners, especially those in ruins or pyramid basements, weren't spawning anything even during the proper time of day. This was confirmed when a friend tried to make a grind room; and no barbarians have spawned over a long period of time.

**Comment by GirafiStudios** [comment]
Thank you for the report!
You're indeed correct, that this is an issue - mostly in the pyramid basement.
Bandit spawners would still need enough daylight to function properly

**Comment by Azuriuz** [comment]
ok awesome, thank you!
