### ISSUE TITLE
Suggestion - Concrete Powders

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/Atum2#143]
Would be great to be able to craft concrete powder. In vanilla it's made with sand, gravel, and dye. Can we get a crafting recipe for it that uses strange sand, dyes, and limestone gravel?

Original recipe and info here: https://minecraft.gamepedia.com/Concrete_Powder

**Comment by SoldierKucha** [comment]
You already can craft Strange Sand into normal Sand cant you?
