### ISSUE TITLE
Spawners Still Not Spawning

### ISSUE THREAD

**Issue by ShadowGeneral** [TeamMetallurgy/Atum2#147]
For some reason mob spawners in underground ruins are Not Spawning. How exactly do you fix this?

I am on version 1.12.2 right now.

**Comment by GirafiStudios** [comment]
What Atum version are you using?

**Comment by ShadowGeneral** [comment]
2.0.10

**Comment by GirafiStudios** [comment]
If you had looked on CurseForge, you could have seen  that it was fixed in 2.0.11

**Comment by ShadowGeneral** [comment]
Sorry. I was unaware that there was an update.
