### ISSUE TITLE
Mobs can't get through Atum 2 portal

### ISSUE THREAD

**Issue by iWERTSQ** [TeamMetallurgy/Atum2#149]
Mod Version: Atum-1.12.2-2.0.12
Forge: forge1.12.2-14.23.5.2838
Modpack: Custom

None of the mobs can get through the portal. This is a problem for the players who want to bring their pets to the dimension with them or have some kind of mob transportation system between overworld and atum 2 dimension.

**Comment by GirafiStudios** [comment]
Intended behavior.
