### ISSUE TITLE
The Desert Hoards

### ISSUE THREAD

**Issue by Bufavolous-The-Wind-Lord** [TeamMetallurgy/Atum2#150]
I am wondering if, perhaps, the spawn rate of bandits during the day and undead during the night, could perhaps be turned down a tad?
I understand if you and those in your testing group are capable of handling/prefer large groups of enemies assailing you at all times, but not everyone is fond constantly of wading through small armies of enemies.
Perhaps a config option to customize that to a user's preference?
Thank you for taking the time to read this.

Regards,
                ~ The Wind-Lord, Bufavolous

**Comment by GirafiStudios** [comment]
Unfortunately that is not currently possible for Minecraft 1.12
