### ISSUE TITLE
[Suggestion] Better water fail

### ISSUE THREAD

**Issue by scribbler957** [TeamMetallurgy/Atum2#151]
I'd like to suggest that instead of the nether steam effect, placing water above ground outside oases adds a flowing water block (going in the directing the player is facing). Vanilla mechanics will cause water to spread out and rapidly fade away as it's absorbed into the ever parched sands.

The Antimatter Chemistry modpack got me thinking of limestone as a calcium source, so I have this image of Atum as being made of the bones of the dead mixing with the original sand for aeons until this ever-thirsty land was the result.

**Comment by GirafiStudios** [comment]
That's not possible if Atum should still support prevention of modded fluid types (That are similar to water) to be placed.
It is a good idea though, unfortunately not possible currently.

**Comment by scribbler957** [comment]
Out of curiosity (I don't know the modding APIs), it's more complicated to add flowing blocks of other liquids?
