### ISSUE TITLE
[Feature Request] Config option to disable Oasis

### ISSUE THREAD

**Issue by Intipablo** [TeamMetallurgy/Atum2#152]
Currently working on a modpack and wanted to prevent the Oasis from being generated, but I can't find anything about it in the config file. Just wondering if it would be possible to add a weight option to it like the other biomes in the mod.

Thanks for the great mod and keep up the good work

**Comment by GirafiStudios** [comment]
The Oases biomes is a sub biome so they do not have a weight like a normal biome does.
I've added two config option though that let's you have full control over the rarity over Oases and the the distribution of Oasis vs. Dead Oasis.
You can go grab a build with the config option in here: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%20Jenkins/81/

**Comment by Intipablo** [comment]
Cheers mate, thanks for the quick response 👍
