### ISSUE TITLE
[Feature Request] Config Option to allow Dirt/Grass

### ISSUE THREAD

**Issue by Intipablo** [TeamMetallurgy/Atum2#153]
Sorry haha but I'm back, just wondering if it would be possible to add a config option to allow the placing of blocks like Dirt/Grass/Podzol and all that?

I know it sounds dumb because I could just leave Oases in and plant saplings from there but I'm trying to do something with this pack and this option would be great if possible.

**Comment by GirafiStudios** [comment]
You have Fertile Soil which is basically grass, just needs some water nearby (Similar how to Farmland requires water).
I'm not going to allow to the placing of dirt, grass etc., since it breaks the balance of stuff in Atum

**Comment by GirafiStudios** [comment]
A config option to control what Y-level water vaporizes is fair. Just pushed it, Jenkins build should be done in a bit :)

**Comment by Intipablo** [comment]
Cheers mate.
