### ISSUE TITLE
Kiln crafttweaker issues

### ISSUE THREAD

**Issue by oly2o6** [TeamMetallurgy/Atum2#164]
When adding new recipes to the kiln everything was going fine but then we kindof hit a point when we add a new recipe to it, other recipes we are also adding randomly vanish as if we can’t add more than a set number or new recipes to it

**Comment by GirafiStudios** [comment]
Could you try sending me a script that makes the problem occur?

**Comment by GirafiStudios** [comment]
Closing because of no response.
Please open a new issue with more information, if the issue still persist for you.
