### ISSUE TITLE
instant tp back trough the portal

### ISSUE THREAD

**Issue by malmiteria** [TeamMetallurgy/Atum2#167]
hi!

my computer is kinda slow so it plays a role in this, but it happens it sometimes need a fair amount of time to load the world the opposite side of the portal.
Since there is a delay before tping back, i should have time to leave the portal once entered the over dimension, but since my computer is slow, I can't always moove in that timeframe. When this happens I'm stuck tping 5 to 10 times before i can manage to get out of the portal.
Is it possible to disable tp back unless I left the portal, like the nether portal? I don't know how exactly, maybe adding a tag turning true only when leaving the portal and turning false only when going through.

Thanks!

**Comment by GirafiStudios** [comment]
Make sure you're on the latest version. This was an issue for some people quite a while back, but it got changed to mimic the Nether Portal countdown.
