### ISSUE TITLE
Heart of Ra can be placed and destroyed again

### ISSUE THREAD

**Issue by MarioSMB** [TeamMetallurgy/Atum2#168]
The beacon-like block entity you find at the top of lighthouses explodes when hit, dropping the heart item. This item can then be placed anywhere and cause another explosion, effectively acting as instant TNT.  
Perhaps this item should not be placeable until it is crafted into the beacon?

**Comment by Azuriuz** [comment]
I really enjoy placing the heart of ra as a deco item; instead maybe it explodes but does not damage nearby blocks? Or maybe have a config to turn off heart of ra griefing, or something?

It would be a shame if we couldn't place it in the world, but I agree unlimited tnt is not good. Hopefully there's some way to balance this without losing the decorative aspect.

**Comment by GirafiStudios** [comment]
Intended.
