### ISSUE TITLE
Raider camps

### ISSUE THREAD

**Issue by MarioSMB** [TeamMetallurgy/Atum2#169]
Rather than spawning those Efreet men everywhere throughout the deserts during the daytime, it would be nice to instead spawn them only around a new structure: camps.  
These camps would contain some kind of treasures in the tents or whichever structures they're made out of, providing incentive for a well equipped player to raid the camp and defeat all the Efreet.

This would help reduce the repetitive nature of constantly running into identical-looking men shouting "huh-huh!" wherever you go, allowing the deserts to feel more vast and desolate.

**Comment by GirafiStudios** [comment]
There is plans for camps in the future.
