### ISSUE TITLE
Crash whenever I enter dimension

### ISSUE THREAD

**Issue by Nessark007** [TeamMetallurgy/Atum2#170]
For some reason it crashes whenever I enter the dimension
https://paste.dimdev.org/owowowicub.mccrash

**Comment by sscards55** [comment]
This doesn't look like an Atum crash.
Backup your world and try removing Galacticraft (and Micdoddle core).

**Comment by GirafiStudios** [comment]
As sscards said, this does not seem to be an issue related to Atum. Some mob is crashing when trying to get spawned, and the stack trace would look different due to how Atum adds mob spawning to the dimension.
