### ISSUE TITLE
Tamed stoneguards and stonewardens marked hostile

### ISSUE THREAD

**Issue by SamuraiShogun1102** [TeamMetallurgy/Atum2#171]
When I created stoneguards or stonewardens, they are marked hostile and cause golems and modded guard npcs to attack them.

**Comment by GirafiStudios** [comment]
Unfortunately due to how this is coded, I can't fix it in 1.12.2 without breaking Stoneguards/Stonewardens in exciting worlds.
I'll keep this as a reminder for the future.

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/TeamMetallurgy/Atum2/commit/6e6dbbed9b9a93e6ee10c641c7e382b41b984004
