### ISSUE TITLE
Artifact not repairing with mending on

### ISSUE THREAD

**Issue by dvxrek** [TeamMetallurgy/Atum2#172]
Shu's Swiftness does not repair when earning experience. I have mending on it and I've tested with bottles of enchanting as well.

**Comment by GirafiStudios** [comment]
Technically it does, the "problem" is that mending only applies for stuff that's equipped - so armor or held items. But when Shu's Swiftness is held it also uses durability, so having mending on it and picking up experience will just decrease the amount of durability used - which is intended :)
