### ISSUE TITLE
atum dimension is empty

### ISSUE THREAD

**Issue by lanowar150** [TeamMetallurgy/Atum2#175]
i was putting together a modpack for me and my friends to enjoy i wanted to add this mod but its completly empty its just a empty endless desert. does someone know how to fix this if you need full mod list just ask

**Comment by GirafiStudios** [comment]
Probably one of the other mods you're using that's breaking stuff.
Closing this for now as no useful information have been provided. If you figure out what mod(s) is causing the issues, please report back :)
