### ISSUE TITLE
Atum 2 causes graphical glitches with Botania when shaders are used

### ISSUE THREAD

**Issue by Fallayn** [TeamMetallurgy/Atum2#176]
Hi, using the most recent version of Atum 2, when I use the wand of the forest on a Mana Spreader from Botania the visible effect is missing. Normally, the selected Mana Spreader block gets highlighted, also the currently targeted block gets highlighted.

Those effects are missing. If I disable Atum 2, the visual highlight works again.

This is happening in the overworld dimension.

**Comment by GirafiStudios** [comment]
Thanks for your report!
Please provide some screenshots, so I know exactly what I'm looking for.

**Comment by Fallayn** [comment]
You're welcome, and thanks for the fast response! (And for the mod, obviously :))

After playing around with it some more, it seems to only happen while using Optifine and a shader.
If you don't want to support that, you can of course close this issue :)
It **does** work fine without Autum 2 installed however, even with the same setup.

I'm using the latest 1.12.2 Optifine and the SEUS Renewed 1.0.0 shader.

So, in Creative you can place 2 or 3 *Mana Spreader*s down somewhere. Also give yourself a *Wand of the Forest* (color doesn't matter).

Now with the *Wand of the Forest* in hand, Shift+Right click on one of the *Mana Spreader*s.

![2020-03-28_18 23 25](https://user-images.githubusercontent.com/30709206/77829266-4d1fa380-7121-11ea-945b-b145711ad07a.png)

See the colored outline around the *Mana Spreader*? That means it was selected successfully.
Now Shift+Right click on another spreader, and the selected *Mana Spreader* should rotate to point at it. If you now hover over the first spreader, the one it is targeting should get highlighted:

![2020-03-28_18 25 21](https://user-images.githubusercontent.com/30709206/77829302-7fc99c00-7121-11ea-85ce-ca15809d2204.png)

The highlight colors are randomly changing over time. But **with Atum 2 installed**, the highlights are completely missing - for comparison:

![2020-03-28_18 38 55](https://user-images.githubusercontent.com/30709206/77829638-8f49e480-7123-11ea-91d4-3279df199a36.png)

Note the missing highlight on the targeted block. Same for the Shift+Rightclick selected block highlight. Again, without shaders it works fine with Atum, but without Atum it works fine *with shaders* - which is a shame, as Atum otherwise seems to work fine with the shader too. :(

For what it's worth, I tried disabling the fog in Atum 2 in the config but that didn't help. I also haven't tested if there are other similar things impacted in Botania or other mods.

**Comment by GirafiStudios** [comment]
I'll take a look a it later, since you can reproduce it without Optifine.

**Comment by GirafiStudios** [comment]
I'm unable to reproduce the issue with just Atum and Botania, would you happen to be using Optifine still?
https://i.imgur.com/HPrXguE.png

**Comment by GirafiStudios** [comment]
Closing because of no response.
Let me know if you're able to reproduce this without Optifine though :)
