### ISSUE TITLE
error:a recipes for 'atum:kiln_recipes Entries: [atum:redstone_ore_redstone]'

### ISSUE THREAD

**Issue by ACSBlock** [TeamMetallurgy/Atum2#177]
1.12.2:error:a recipes for 'atum:kiln_recipes Entries: [atum:redstone_ore_redstone]' doesn't match client with server.
I installed atum2 latest on client and server,when i try to join the server,it show that "fatally missing registery entries",then i check the log,I got the problem in [atum:redstone_ore_redstone],please fix it,thx
![BR58RKIX~AWILY ~YBWNU7K](https://user-images.githubusercontent.com/21095880/77926310-923a0600-72d8-11ea-8aee-a4be9b1b9025.png)

**Comment by sscards55** [comment]
can you provide your log from both the server and the client?

**Comment by ACSBlock** [comment]
yeah,there is
[debug_and_log.zip](https://github.com/TeamMetallurgy/Atum2/files/4403609/debug_and_log.zip)

**Comment by GirafiStudios** [comment]
Try using the command: /fml confirm , in the server console.

**Comment by sscards55** [comment]
It looks like something is trying to register the recipe twice on the server, but not on the client for some reason.

**Comment by ACSBlock** [comment]
okay,might be i got wrong,thx your advice
