### ISSUE TITLE
[1.12.2] [Feature Request] Support for modded caves

### ISSUE THREAD

**Issue by yungnickyoung** [TeamMetallurgy/Atum2#178]
Hey, I'd like to be able to override the caves with my own mod. From a brief look at the code, this doesn't seem to be possible.

I believe the change should be pretty easy. Instead of the following:
https://github.com/TeamMetallurgy/Atum2/blob/5093b2a6d54e204aedd6d7dc7fd8f2854907d515/src/main/java/com/teammetallurgy/atum/world/ChunkGeneratorAtum.java#L59

It would be something like
```java
private MapGenBase caveGenerator = TerrainGen.getModdedMapGen(new MapGenCaves(), EventType.CAVE);
```

Let me know what you think!

**Comment by GirafiStudios** [comment]
Sure, why not :)
Will be a bit before it makes it into a release most likely, but you can grab a jar here for now:
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.12.2%20Jenkins/99/
