### ISSUE TITLE
Camel created AssertionError, crashes server

### ISSUE THREAD

**Issue by SauROnmiKE** [TeamMetallurgy/Atum2#179]
Hi there!

I was testing out the mod and I went to explore the new dimension. After loading some chunks I happened to see camel and the server immediately crashed, generating the following report:

https://pastebin.com/yhzdEqYi

Please tell me if you need any additional info. Have a nice day and stay safe!

**Comment by GirafiStudios** [comment]
The crash is caused by CraftBukkit.

**Comment by SauROnmiKE** [comment]
Thanks for the very quick response and sorry for opening again, but any suggestions about that? I know it's not caused by Atum, I am just very new to PaperSpigot and I thought there could be some sort of workaround. Sorry for opening again.

**Comment by GirafiStudios** [comment]
Unfortunately I know very little about Spigot, let alone PaperSpigot (Whatever that is). If you figure out what exactly is causing the issue, feel free to respond back.
I know for a fact that Atum 2 does work with Spigot, so it must be a problem with how PaperSpigot does things.

**Comment by SauROnmiKE** [comment]
Paper just gives tons of configuration on Spigot and general performance improvement.
I could try just a Spigot/Forge hybrid. Disabling camels entirely from the config also helped, but what's the point then? Camels are awesome.
