### ISSUE TITLE
Suggestion: Sandstorm in overworld desert transports to atum & Fulgurite

### ISSUE THREAD

**Issue by ShadowDMA** [TeamMetallurgy/Atum2#180]
Just thought it would be cool if sandstorms could happen in the overworld desert biome that limits your visibility and if you don't go somewhere safe by the time the sandstorm dissipates you are teleported to atum, also another thing that came the mind was maybe you've heard of Fulgurite a crystal that forms when lightning strikes sand, a sandstorm can build up static electricity which causes lightning making fulgurite which is viewed by some cultures as a sort of crystalline form of a god's energy

**Comment by GirafiStudios** [comment]
Thanks for your suggestions!
Atum does by design not touch the Overworld, or require anything from the overworld, so the sandstorm in the Overworld Desert it outside the scope of the mod.
Fulgurite might maybe be something we look into in the future, as it does occur in the Saharan Desert.
