### ISSUE TITLE
Spawner BUG (Once player close to the spawner in the desert, server creashed)

### ISSUE THREAD

**Issue by GriffinChen** [TeamMetallurgy/Atum2#181]
---- Mohist 崩溃报告 ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

崩溃时间: 20-6-10 下午1:50
描述: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:377)
	at net.minecraft.world.World.addEntity(World.java:1463)
	at net.minecraft.world.WorldServer.addEntity(WorldServer.java:1354)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:206)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:618)
	at java.lang.Thread.run(Unknown Source)

错误的详细信息，其代码路径和所有已知的细节如下所示:
---------------------------------------------------------------------------------------

-- 开始 --
线程名: Server thread
堆栈跟踪:
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:377)
	at net.minecraft.world.World.addEntity(World.java:1463)
	at net.minecraft.world.WorldServer.addEntity(WorldServer.java:1354)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:206)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:423)

-- Affected level --
Details:
	Level name: DIM17
	All players: 1 total; [EntityPlayerMP['NG_CE'/3316, uuid='194bb5a8-deba-3efc-9af1-8fa4d225f73a', l='DIM17', x=-372.40, y=69.00, z=327.51, cx=-24, cd=20, tl=31405, v=true, d=false](NG_CE at -372.399865179517,69.0,327.50517566889187)]
	Chunk stats: ServerChunkCache: 462 Drop: 0
	Level seed: 6957940415796623553
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 132800 game time, 132800 day time
	Level dimension: 17
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:618)
	at java.lang.Thread.run(Unknown Source)

-- 系统详情 --
Details:
	Mohist版本: 1.12.2-bb39330
	操作系统: Windows Server 2016 (amd64) 版本 10.0
	JAVA版本: 1.8.0_251, Oracle Corporation
	JAVA虚拟机版本: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	内存: 24781867544 bytes (23633 MB) / 26843545600 bytes (25600 MB) up to 26843545600 bytes (25600 MB)
	JAVA虚拟机参数: 5 total; -Xms25600M -Xmx25600M -XX:+UseG1GC -XX:+AggressiveOpts -XX:+UseCompressedOops
	内部缓存: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	CraftBukkit信息: 
   Running: Mohist version git-Spigot-1.12.2-bb39330 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) false
   Plugins: { NoPlugins v7.2 me.xanium.noplugin.NoPlugins [Xanium], WorldEdit v6.1.9;caf0ad9 com.sk89q.worldedit.bukkit.WorldEditPlugin [], DoubleJump v1.0 de.guzel.doublejump.main.Main [guzel], ArmorReplace v3.0 me.pandaAR.Main [JackThePanda], AggressiveAnimals v2.4 com.michielcx.aggressiveanimals.AttackPlugin [Michielcx], PlaceholderAPI v2.9.2 me.clip.placeholderapi.PlaceholderAPIPlugin [[extended_clip]], GroupManager v2.0.1-b332 org.anjocaido.groupmanager.GroupManager [AnjoCaido, Gabriel Couto, ElgarL], Hat v1.2.1 net.woek.Hat.Hat [], Vault v1.7.2-b107 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], ProtocolLib v4.4.0 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], WowSuchCleaner v1.9.1 io.github.Cnly.WowSuchCleaner.WowSuchCleaner.Main [Cnly], Essentials v2.15.0.52 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, md678685], AntiAttack v1.0.0 com.relatev.minecraft.antiattack.bukkit.AntiAttackBK [], EssentialsChat v2.15.0.52 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], EssentialsSpawn v2.15.0.52 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], AuthMe v5.4.0-b1877 fr.xephi.authme.AuthMe [Xephi, sgdc3, DNx5, timvisee, games647, ljacqu, Gnat008],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Craft Scheduler Thread - 10: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), io.github.Cnly.WowSuchCleaner.Crafter.Crafter.framework.configs.AbstractConfigManager$AsynchronousSavingConsumerTask.run(AbstractConfigManager.java:244), org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:77), org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:50), com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #2: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #1: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Unknown Source)], RUNNABLE Server console handler: [org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method), org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:761), org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794), org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97), jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214), jline.WindowsTerminal.access$000(WindowsTerminal.java:54), jline.WindowsTerminal$1.read(WindowsTerminal.java:156), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243), jline.internal.InputStreamReader.read(InputStreamReader.java:257), jline.internal.InputStreamReader.read(InputStreamReader.java:194), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2126), jline.console.ConsoleReader.readBinding(ConsoleReader.java:2211), jline.console.ConsoleReader.readLine(ConsoleReader.java:2460), jline.console.ConsoleReader.readLine(ConsoleReader.java:2372), net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:121)], WAITING ProtocolLib-StructureCompiler 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_12_R1.CraftCrashReport.call(CraftCrashReport.java:27), net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:122), net.minecraft.crash.CrashReport.<init>(CrashReport.java:43), net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:347), net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:892), net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468), net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:618), java.lang.Thread.run(Unknown Source)], TIMED_WAITING threadDeathWatcher-2-1: [java.lang.Thread.sleep(Native Method), io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152), io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144), java.lang.Thread.run(Unknown Source)], WAITING Forge Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Craft Async Scheduler Management Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:51), net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Thread-10: [java.lang.Thread.sleep(Native Method), com.relatev.minecraft.antiattack.bukkit.protocol.AntiFastPacketAttack.lambda$init$0(AntiFastPacketAttack.java:47), com.relatev.minecraft.antiattack.bukkit.protocol.AntiFastPacketAttack$$Lambda$192/785970478.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING Timer-1: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:95)], WAITING Forge Chunk I/O Executor Thread-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING pool-9-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #3: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Unknown Source)], WAITING TerminalConsoleWriter - 2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77), org.bukkit.craftbukkit.v1_12_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:29), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.lang.ref.Reference.tryHandlePending(Unknown Source), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 14: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #0: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Unknown Source)], TIMED_WAITING mysql-cj-abandoned-connection-cleanup: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:85), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-8-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Mohist Async Task Handler Thread - 1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-10-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Metrics - 3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Craft Scheduler Thread - 15: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Attach Listener: [], TIMED_WAITING Async Chat Thread - 6: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Abandoned connection cleanup thread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)],}
   
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version        | Source                                | Signature                                |
	|:------ |:------------------- |:-------------- |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2         | minecraft.jar                         | None                                     |
	| LCHIJA | mcp                 | 9.42           | minecraft.jar                         | None                                     |
	| LCHIJA | mohist              | 1.6            | mohist.jar                            | None                                     |
	| LCHIJA | FML                 | 8.0.99.99      | Mohist-bb39330-server.jar             | None                                     |
	| LCHIJA | forge               | 14.23.5.2847   | Mohist-bb39330-server.jar             | None                                     |
	| LCHIJA | atum                | 2.0.17         | Atum-1.12.2-2.0.17.jar                | None                                     |
	| LCHIJA | magic_mirror        | 1.12.2-0.0.4.0 | magic-mirror-1.12.2-0.0.4.0.jar       | None                                     |
	| LCHIJA | mobends             | 0.24           | mobends-0.24_for_MC-1.12.jar          | None                                     |
	| LCHIJA | swordblockingcombat | 1.0.2          | SwordBlockingCombat-v1.0.2-1.12.2.jar | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 4 / 50; [EntityPlayerMP['Red_Reisen'/7195, uuid='f3217883-9125-3969-abda-80b04b559af8', l='world', x=-74.25, y=81.17, z=-507.16, cx=-5, cd=-32, tl=26503, v=true, d=false](Red_Reisen at -74.2527468144576,81.16610926093821,-507.15752226192564), EntityPlayerMP['NG_CE'/3316, uuid='194bb5a8-deba-3efc-9af1-8fa4d225f73a', l='DIM17', x=-372.40, y=69.00, z=327.51, cx=-24, cd=20, tl=31405, v=true, d=false](NG_CE at -372.399865179517,69.0,327.50517566889187), EntityPlayerMP['Griffin_CYZ'/72, uuid='e7ce2df3-c2ce-3029-b3df-a2984611163e', l='world', x=-80.69, y=82.75, z=-497.76, cx=-6, cd=-32, tl=82634, v=true, d=false](Griffin_CYZ at -80.68694928327088,82.7531999805212,-497.76370832133085), EntityPlayerMP['HFty'/13075, uuid='eec5d219-b2d1-3901-825b-74760f300a50', l='world', x=-254.89, y=64.00, z=496.62, cx=-16, cd=31, tl=6685, v=true, d=false](HFty at -254.88533742565218,64.0,496.61902010220217)]
	Is Modded: Definitely; Server brand changed to 'Mohist'
	Type: Dedicated Server (map_server.txt)

**Comment by GriffinChen** [comment]
The camel egg can't spawn camel...

**Comment by GirafiStudios** [comment]
Thanks for your report!
Unfortunately this issue is caused by Spigot, can't really do anything about it.
