### ISSUE TITLE
1.15.2 One Probe Related Crash

### ISSUE THREAD

**Issue by MokahTGS** [TeamMetallurgy/Atum2#184]
Getting a crash on load in SP with the One Probe and the latest version of Atum 1.15.2

MC: 1.15.2
Forge: 31.2.30
Atum 2: Atum-1.15.2-2.1.0

Full Mod List: https://pastebin.com/kNUTphbC

Log file: https://pastebin.com/rxdqqxrT

There isn't a CTD, just MC giving me a problem loading error and that was in the log.  Taking Atum out stops the crash.

**Comment by GirafiStudios** [comment]
Thanks for your report!
You can grab a build with the fix from the Jenkins here https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.15.2%20Jenkins/3/ :)
