### ISSUE TITLE
1.15.2 Server Crash

### ISSUE THREAD

**Issue by MokahTGS** [TeamMetallurgy/Atum2#186]
Getting a crash with our server trying to load Atum-1.15.2-2.1.1.alpha3

MC: 1.15.2
Forge: 31.2.30
Atum-1.15.2-2.1.1.alpha3

https://pastebin.com/0k9YL5h9

**Comment by sscards55** [comment]
already fixed in #185

**Comment by MokahTGS** [comment]
heh...you're too fast
