### ISSUE TITLE
[Atum-1.15.2-2.1.1.jar] Sarcophagus Client Rendering Crash

### ISSUE THREAD

**Issue by GatekeeperTDS** [TeamMetallurgy/Atum2#189]
Hi - Not sure what could be causing this, or if it's an issue with Atum or with JEI, but we're experiencing a client crash when JEI attempts to display the sarcophagus.

We've tried it with and without Optifine and the same thing happens.

Unfortunately, JEI hasn't updated in quite some time, and has no configuration (with a nearly year-old open issue regarding a lack of a config file for 1.13 - 1.15 versions).

Is there a way to hide the sarcophagus from JEI in another way?

Thank you. Relevant crash details below -

Description: Rendering item

java.lang.NullPointerException: Rendering item

Details:
	Item Type: sarcophagus
	Registry Name: atum:sarcophagus
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:383)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:37)

**Comment by GatekeeperTDS** [comment]
Small update to this, I tried to /give myself the sarcophagus item as well and it crashed, so this seems to be an issue with rendering the sarcophagus and nothing to do with JEI. Attaching the full log. Thank you.
[crash-2020-07-11_16.04.40-client.txt](https://github.com/TeamMetallurgy/Atum2/files/4907537/crash-2020-07-11_16.04.40-client.txt)

**Comment by GirafiStudios** [comment]
This seems to be caused by Cooking For Blockheads for some reason. Not really too familiar with the mod, but they must be trying to look up something in relation to TEs

**Comment by GirafiStudios** [comment]
I've made a PR to Cooking for Blockheads, which fixes the issue: https://github.com/blay09/CookingForBlockheads/pull/455
