### ISSUE TITLE
When attempting to load a lighthouse, an error occurs in the server with the Sunspeaker entity

### ISSUE THREAD

**Issue by sukiyu000** [TeamMetallurgy/Atum2#192]
This error only occurs on server instances, I was never able to replicate it on a local singleplayer instance.

Forge version: 31.2.32
    Mod List ripped straight from server logs:
        forge-1.15.2-31.2.31-server.jar Minecraft {minecraft@1.15.2 DONE}
        useful_backpacks-1.15.2-1.10.1.66.jar Useful Backpacks {usefulbackpacks@1.10.1.66 DONE}
        repurposedstructures-1.15.2-1.7.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.7.2 DONE}
        pandoras_creatures-1.15.2-1.0.0.jar Pandoras Creatures {pandoras_creatures@1.15.2-1.0.0 DONE}
        Craft_and_Hunt_V1.1.0_MC_1.15.2.jar Craft and Hunt {craftandhunt@0.9 DONE}
        mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
        jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
        Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
        Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
        HammerLib-1.15.2-15.2.3.jar HammerLib {hammerlib@15.2.3 DONE}
        Atmospheric-1.15.2-1.4.1.jar Atmospheric {atmospheric@1.4.1 DONE}
        Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
        BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
        Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
        gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
        journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
        autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
        Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
        AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
        StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
        themidnight-0.5.9.jar The Midnight {midnight@0.5.9 DONE}
        betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
        WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
        Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
        The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
        snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
        u_team_core-1.15.2-3.0.0.160.jar U Team Core {uteamcore@3.0.0.160 DONE}
        ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
        AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
        Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
        forge-1.15.2-31.2.31-universal.jar Forge {forge@31.2.31 DONE}
        Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
        Atum-1.15.2-2.1.3.jar Atum 2 {atum@1.15.2-2.1.3 DONE}
        Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 DONE}
        wendigoism-1.1.2.jar Wendigoism {wendigoism@1.1.2 DONE}
        dash-1.15.2-1.0.1.jar Dash {dash@1.0.1 DONE}
        RottenCreatures-1.15.2-0.9.7.jar Rotten Creatures {rotten_creatures@0.9.7 DONE}

When I replicated this error on my own server, just to see if this was an isolated instance, my servers console gave this error when I came close to the lighthouse structure:
`[09:09:04] [Server-Worker-14/INFO] [STDOUT/]: [com.teammetallurgy.atum.world.gen.structure.lighthouse.LighthousePieces$LighthouseTemplate:spawnSunspeakers:79]: While
[09:09:04] [Server-Worker-14/INFO] [STDOUT/]: [com.teammetallurgy.atum.world.gen.structure.lighthouse.LighthousePieces$LighthouseTemplate:spawnSunspeakers:97]: add sunspeaker
[09:09:04] [Server-Worker-14/INFO] [STDOUT/]: [com.teammetallurgy.atum.world.gen.structure.lighthouse.LighthousePieces$LighthouseTemplate:spawnSunspeakers:79]: While
[09:09:04] [Server-Worker-14/INFO] [STDOUT/]: [com.teammetallurgy.atum.world.gen.structure.lighthouse.LighthousePieces$LighthouseTemplate:spawnSunspeakers:97]: add sunspeaker
[09:09:04] [Server-Worker-14/INFO] [STDOUT/]: [com.teammetallurgy.atum.world.gen.structure.lighthouse.LighthousePieces$LighthouseTemplate:spawnSunspeakers:79]: While
[09:09:04] [Server-Worker-14/INFO] [STDOUT/]: [com.teammetallurgy.atum.world.gen.structure.lighthouse.LighthousePieces$LighthouseTemplate:spawnSunspeakers:97]: add sunspeaker
[09:09:04] [Server thread/INFO] [minecraft/DedicatedServer]: [Sukiyu: Teleported Sukiyu to 192.5, 90.72269083441569, 176.5]
[09:09:06] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: Sukiyu lost connection: Disconnected
[09:09:06] [Server thread/INFO] [minecraft/DedicatedServer]: Sukiyu left the game
[09:09:09] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (atum): All chunks are saved`

**Comment by sukiyu000** [comment]
Whenever going near the lighthouse on the server, the server kicks you out with this error message: `io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information:`
This only occurred after we went near the lighthouses.

**Comment by sukiyu000** [comment]
Oh wait, I'm sorry! I grabbed the wrong error:
https://prnt.sc/tjdg7s

**Comment by GirafiStudios** [comment]
You can grab a build with the fix here: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.15.2%20Jenkins/ 
Will probably be a day or two, before it makes it into a release on CurseForge.
