### ISSUE TITLE
Cant craft mod itens on multiplayer

### ISSUE THREAD

**Issue by VetGet** [TeamMetallurgy/Atum2#193]
Me and my friends cant craft the items from de Atum 2, items are the same as vanilla, or the recipe won exist.

**Comment by GirafiStudios** [comment]
Can you try rephrasing your issue? I'm not really sure what you're trying to say.

**Comment by VetGet** [comment]
We are having trouble creating mod items, some are simply not generating anything from the recipe and are built or replaced with standard game items

**Comment by GirafiStudios** [comment]
Could you please provide a few examples? Preferably just screenshots of the recipe not working.

**Comment by Waltorias** [comment]
Hi, I have the same problem, I can't craft the scarab to get into the portal in MP on the modpack Valhelsia 2 v2.2.2a, Minecraft v1.15.2, forge-31.2.0
image of the bug : 
![bug-mp-valhelsia2-2 2 2a](https://user-images.githubusercontent.com/68472970/87855650-fb8e6500-c919-11ea-951f-c27a3c2fedde.png)

(Or we don't craft the scarab and I missed smth ?) 

Thank you !

**Comment by GirafiStudios** [comment]
Unable to reproduce on a server. I assume it's being changed in the modpack you're playing.
Would you happen to be playing with VetGet, or just happened to have a similar issue?
![s9LXbMH](https://user-images.githubusercontent.com/6305377/87855980-4315f080-c91c-11ea-8318-6c18f9659482.png)

**Comment by GirafiStudios** [comment]
Looking at the modpack versions, looks like Atum 2 got added 7 hours ago in version 2.2.5a
 of the modpack :)

**Comment by Waltorias** [comment]
Ok, thank you :) !!
