### ISSUE TITLE
[1.15.2] Questions about textures

### ISSUE THREAD

**Issue by TheUntamed** [TeamMetallurgy/Atum2#201]
Hi,

I'm creator of the mod https://www.curseforge.com/minecraft/mc-mods/dannys-ores which adds all types of ores for a lot of stone variants. I would like to do this for your mods stone variants and ore types (bone, relic) too and wanted to ask if I can use the Limestone, Alabaster, etc. textures for that?

**Comment by GirafiStudios** [comment]
As long as you don't ship the textures directly in your mod, it would be totally fine :)
There is a guide how to add Atum to your build.gradle in the readme
