### ISSUE TITLE
Crash with Assassin

### ISSUE THREAD

**Issue by Divineaspect** [TeamMetallurgy/Atum2#203]
https://pastebin.com/ms4tbm2

**Comment by sscards55** [comment]
The log you posted has been removed from the site.

**Comment by Divineaspect** [comment]
Wierd lets try that again.
https://pastebin.com/agXSveEX

**Comment by Vaelzan** [comment]
I've noticed that this happens every single time a player on my server teleports away from Atum to the Overworld (usually via the Waystones mod) while near an assassin, crashing the server. Very reproducible. (Valhelsia: Origins pack)

This gives me a bit of a hint towards what might be causing it but I haven't had a chance to look at the code to confirm my suspicions.

**Comment by GirafiStudios** [comment]
Unable to reproduce this, using Velhelsia Origins on a server + using Waystones to teleport away from an Assassin that have you as a target.

**Comment by Vaelzan** [comment]
[crash-2020-08-16_19.27.50-server.txt](https://github.com/TeamMetallurgy/Atum2/files/5081100/crash-2020-08-16_19.27.50-server.txt)
[crash-2020-08-16_18.56.04-server.txt](https://github.com/TeamMetallurgy/Atum2/files/5081101/crash-2020-08-16_18.56.04-server.txt)


Couple of examples there from yesterday.

**Comment by GirafiStudios** [comment]
It's very clearly being caused by the Assassin from the crash log, but the problem is that if I can't reproduce it I can't attempt to fix it.  As where it's crashing isn't really telling me much.
I've tried something though, if you could try out this build with an attempt fix - that would be great!
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.15.2%20Jenkins/21/

**Comment by GirafiStudios** [comment]
@Divineaspect & @Vaelzan any chance I could get either of you to try out the fix?

**Comment by Vaelzan** [comment]
Hi, sorry, I really want to since I'd love to have a fix available but I've been incredibly unwell recently and haven't been able to sit upright for long.

**Comment by GirafiStudios** [comment]
The attempted fix will be available in 2.1.5 on CurseForge shortly.
Please open a new issue, if you experience the crash on that version.
