### ISSUE TITLE
Lighthouse Config option - 1.15.2 - Forge 31.2.33 - Atum 2.1.4

### ISSUE THREAD

**Issue by Shtreudel** [TeamMetallurgy/Atum2#205]
**I was requested to submit an issue ticket on this matter after speaking with Girafi in the atum discord.

I am attempting to mess with the generation of the lighthouse structure. I've been informed that it is distinctly different from ruins and therefore will not be affected by changing the "Ruins Amount" value in the config file. As lighthouses are the only source of the "Heart of Ra" I was wondering if a future release will include the ability to adjust spawn settings related to the lighthouse?

Please and thank you =)

**Comment by GirafiStudios** [comment]
You can grab a build with config options for all structures here:
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.15.2%20Jenkins/25/
