### ISSUE TITLE
Atum crashes server 

### ISSUE THREAD

**Issue by Joemic97** [TeamMetallurgy/Atum2#207]
Hello I run a small server with me and a few of my friends it seems that whenever somebody dies in the Atum it crashes their Minecraft client. We are playing on the 1.15.2 , any help?

**Comment by sscards55** [comment]
Please provide your crash logs, or at least your mod list and versions of your server.. Without information it's hard to provide help.

**Comment by GirafiStudios** [comment]
No it's not hard to provide help, it's impossible. It's like going to your car mechanic and asking them to fix your car, without providing your car.

**Comment by Joemic2** [comment]
ill send over the crash report in a sec but for now, here is the mod list https://drive.google.com/file/d/1xdM-tb7oJNGFG7Wsu_-LMXhsd4Jq0eEa/view?usp=sharing

**Comment by Joemic2** [comment]
btw that's my alt

**Comment by Joemic2** [comment]
[crash-2020-09-09_14.03.17-client.txt](https://github.com/TeamMetallurgy/Atum2/files/5197171/crash-2020-09-09_14.03.17-client.txt)

**Comment by Joemic2** [comment]
thats the crash report

**Comment by GirafiStudios** [comment]
The crash is caused by VoxelMap. At no point in the stack trace is Atum mentioned - so I cannot even begin to attempt a fix on my side.
