### ISSUE TITLE
[1.12.2] Crash with YUNG's Better Mineshafts using Atum 2.0.18

### ISSUE THREAD

**Issue by aking4125** [TeamMetallurgy/Atum2#210]
Hello!

After updating Atum to 2.0.18 and using YUNG's Better Mineshafts 2.1.0 (Both on 1.12.2). Upon loading a world, the game crashes with the following crash report.

Downgrading Atum to 2.0.17 works. I see in the changelog for Atum that events to Caves & Mineshafts were added, so unknown if YNUG's Bettercaves is also affected by this. 

[crash-2020-09-18_22.17.44-server.txt](https://github.com/TeamMetallurgy/Atum2/files/5250566/crash-2020-09-18_22.17.44-server.txt)

[I was informed by the Author of the other mod to report this here.](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues/19)

**Comment by GirafiStudios** [comment]
Thank you for the report!
Unfortunately it's them who doesn't support the Forge InitMapGenEvent. It was added in the latest build upon request from another mod author.
https://github.com/TeamMetallurgy/Atum2/blob/1.12.2/src/main/java/com/teammetallurgy/atum/world/ChunkGeneratorAtum.java#L61

**Comment by aking4125** [comment]
No worries! Thank you for your quick response.

**Comment by yungnickyoung** [comment]
`private MapGenAtumMineshaft mineshaftGenerator = (MapGenAtumMineshaft) TerrainGen.getModdedMapGen(new MapGenAtumMineshaft(), InitMapGenEvent.EventType.MINESHAFT);`

Can you use a reference to `MapGenMineshaft` or `MapGenStructure` here instead of `MapGenAtumMineshaft`?

**Comment by GirafiStudios** [comment]
I changed it to MapGenStructure, hopefully that did the trick. You can grab a build here: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.12.2%20Jenkins/105/ to check if it worked :)

**Comment by aking4125** [comment]
Just tested that build. Works fine so far!

**Comment by GirafiStudios** [comment]
Alright I'll release a new build on CurseForge sometime later today. Remind me if I haven't.

**Comment by aking4125** [comment]
Yeah. I haven't found an Atum Mineshaft as of yet. Hopefully this did the trick for real.
