### ISSUE TITLE
Achievement Plant these crops.

### ISSUE THREAD

**Issue by Numeric222s** [TeamMetallurgy/Atum2#212]
I have been working hard to complete all the achievements for Atum 2, but now I am confused. I think there is a misunderstanding in the coding for it, saying there are three different types to plant when I see only two emmer and flax. Please fix this or tell me what I am doing wrong. Using version 1.12.2.

**Comment by GirafiStudios** [comment]
Melon Seeds can be found in Atum as well, same as with Emmer and Flax seeds, so it counts in the advancement too.
Please don't use Github for support, use our Discord - there is an invite link to it on our CurseForge page.
