### ISSUE TITLE
Assassin Crash the return of #203

### ISSUE THREAD

**Issue by Divineaspect** [TeamMetallurgy/Atum2#214]
https://pastebin.com/YtwK1yiW

It seems to require the player be marked, there be more then one assassin, and they use Waystone's Warpstone to teleport interdimensionally.

**Comment by GirafiStudios** [comment]
Still unable to reproduce it under those conditions, but I've attempted a fix based on the crashlog, hopefully it works!
You can try it out in the build from here: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.15.2%20Jenkins/

**Comment by CrayolaBlues** [comment]
+1 to this. If I have the Marked effect and elytra/rocket away after a pyramid, the server crashes. pastebin.com/0KzLu5Mz
pastebin.com/JhG0VG1E

**Comment by GirafiStudios** [comment]
> +1 to this. If I have the Marked effect and elytra/rocket away after a pyramid, the server crashes. https://pastebin.com/0KzLu5Mz
> https://pastebin.com/JhG0VG1E

Could you try updating Atum 2 to the latest version, and see if it still happens?

**Comment by GirafiStudios** [comment]
I'm closing this, as there have been no response for 14 days.
The attempted fix is on CurseForge in 2.1.10 or newer.
If you encounter the issue again in that version, please open a new issue!
