### ISSUE TITLE
Atum crashes with Immersive Engineering

### ISSUE THREAD

**Issue by madmax3004** [TeamMetallurgy/Atum2#216]
Server crashes presumably due to Atum 2 / Immersive Engineering issue.

Crash log:

https://pastebin.com/Zk7iYNmc

**Comment by sscards55** [comment]
Minecraft 1.12.2
forge-1.12.2-14.23.5.2854.jar
Atum-1.12.2-2.0.19.jar
ImmersiveEngineering-0.12-98.jar
