### ISSUE TITLE
Some Sort of Desert Wolf Crash

### ISSUE THREAD

**Issue by mahjerion** [TeamMetallurgy/Atum2#217]
Hi, I've encountered a seemingly rare crash. Has only happened once in the months of hosting the Craft to Exile server but thought I'd share it with you anyway.

This is on 1.15.2.

https://pastebin.com/psSeSde3

**Comment by GirafiStudios** [comment]
Thank you very much for the report!
A new version will be available on CurseForge as soon as it's approved.
