### ISSUE TITLE
[Performance] Tefnut's Rain Causing Lag

### ISSUE THREAD

**Issue by Ameranth** [TeamMetallurgy/Atum2#219]
Hello and thank you for your work!

This issue is easily reproduced; simply fire several shots with Tefnut's Rain, allowing it enough distance to perform its special effect. The impact should be more noticeable with more shots fired, but the impact of each shot is removed once the "arrow storm" arrows despawn.

**Comment by GirafiStudios** [comment]
Unable to reproduce any sort of lag with Tefnut's Rain.
Also, no demands.
