### ISSUE TITLE
Crystal Glass Game Crash, Appears as Radiant Beacon on Relaunch

### ISSUE THREAD

**Issue by herb26** [TeamMetallurgy/Atum2#223]
Crystal glass causes rendering incompatibility with Create's blockzapper, and upon nbtedit removal of the item the block appeared as radiant beacons in waila and spawned beacon beams only after the block was looked at and looked away from

**Comment by GirafiStudios** [comment]
Unable to reproduce
![image](https://user-images.githubusercontent.com/6305377/107146766-7f597e80-694a-11eb-960c-701fe9c8452b.png)
