### ISSUE TITLE
Players taking massive damage from portals | Valhelsia 2

### ISSUE THREAD

**Issue by ntjohnst** [TeamMetallurgy/Atum2#224]
I have a Valhelsia 2 server running and we just created the portal.  Whenever someone gets near the portal to come back to the minecraft dimension they take constant unblockable damage.  Whenever  someone goes through the portal they take almost ten hearts of damage.  The server reports deaths as suffocating in walls.

**Comment by GirafiStudios** [comment]
Are you running just Forge on the server, or any sort of Forge/Bukkit hybrid?

**Comment by ntjohnst** [comment]
This only uses Forge straight from the Curse launcher.

Does it matter if the portal structure is created underground?

**Comment by GirafiStudios** [comment]
It could, yeah. The players might be half inside a wall, if there is a wall directly up to the portal of one of the sides

**Comment by ntjohnst** [comment]
You were correct the portal needs space around it suffocates the players.
