### ISSUE TITLE
Random crash in Atum2

### ISSUE THREAD

**Issue by Smackmyhams** [TeamMetallurgy/Atum2#225]
crash-2021-03-21_12.25.56-client.txt

Am unable to press get link 

Game crashes when I walk into certain areas in Atum 2, Doesn't seem to be any place in particular.

**Comment by GirafiStudios** [comment]
You've literally provided zero useful information, so I unfortunately can't help you.
You've not uploaded the crashlog, you've just pasted in the name of it, which is of no use to anyone.

**Comment by Smackmyhams** [comment]
Good morning, the log mustn’t have uploaded. Have a great day!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
