### ISSUE TITLE
Tefnut's Call is not immune to lightning 

### ISSUE THREAD

**Issue by sebkuip** [TeamMetallurgy/Atum2#227]
in #173 tefnut's call was made immune to fire and explosions, but not made immune to lightning. If you hit a mob from above there is a chance it will ricochet upwards into its own bolt and get destroyed.

Minecraft version: 1.12.2
Atum: Atum-1.12.2-2.0.20

**Comment by sebkuip** [comment]
https://cdn.discordapp.com/attachments/607239584962838548/826766916998660106/Jre1.8.0_281_2021.03.31_-_12.35.22.04.mp4
https://cdn.discordapp.com/attachments/607239584962838548/826767231064735764/Tekxit_3.14_Beta_1.12.2_2021-03-31_06-37-11.mp4

2 cases of this happening. On squid (in water) this seems to be much more reliable.

**Comment by GirafiStudios** [comment]
Thanks for the report!
This should no longer be the case in Atum 2.1.0+ (Minecraft 1.15.2+), therefor closing.
1.12.2 is no longer receiving updates, unless something very major comes up.
