### ISSUE TITLE
Crafttweaker support error

### ISSUE THREAD

**Issue by NetherStarStorm** [TeamMetallurgy/Atum2#228]
This mod(atum-1.12.2-2.0.20) does not support crafttweaker. When I change the recipe of the furnace, the recipe of the kiln will not change.

**Comment by sscards55** [comment]
That version of the mod does not exist.

**Comment by sscards55** [comment]
Where did you download the mod from?

**Comment by NetherStarStorm** [comment]
> Can you provide the script?

furnace.remove(<minecraft:glass>);

**Comment by NetherStarStorm** [comment]
> Can you provide the script?

When I reloaded the game, I could not get glass from furnace but kiln was ok.

**Comment by sscards55** [comment]
I don't know if that's intentional, Girafi can confirm, however Atum does have special CT support:
https://atum.fandom.com/wiki/Kiln_CraftTweaker_Support

**Comment by NetherStarStorm** [comment]
> I don't know if that's intentional, Girafi can confirm, however Atum does have special CT support:
> https://atum.fandom.com/wiki/Kiln_CraftTweaker_Support

Thanks, I think I have found the answer. I thought the recipes for furnace and kiln are the same. It was my mistake.
