### ISSUE TITLE
Limestone Door can be used as fuel

### ISSUE THREAD

**Issue by NetherStarStorm** [TeamMetallurgy/Atum2#229]
Limestone door, Cracked Limestone Door and etc can be uesd as fuel. Obviously, limestone is not a fuel.

**Comment by GirafiStudios** [comment]
Unable to reproduce.

**Comment by NetherStarStorm** [comment]
> Unable to reproduce.

It appeared in Atum 1.12.2-2.0.20. I retested it in JEI and furnace and It did happen.
![Snipaste_2021-05-01_18-36-55](https://user-images.githubusercontent.com/70516358/116780032-64f7f280-aaac-11eb-925a-470fe36b38d7.png)

**Comment by GirafiStudios** [comment]
1.12.2 is unsupported by now, Have been fixed in 1.15.2+

**Comment by NetherStarStorm** [comment]
> 1.12.2 is unsupported by now, Have been fixed in 1.15.2+

What a pity. I hope that it can be fixed in 1.12.2. But can I fix it by crafttweaker?
