### ISSUE TITLE
1.16.5 Atum crashes when I enter the Atum portal

### ISSUE THREAD

**Issue by Himynameissomeone** [TeamMetallurgy/Atum2#233]
Currently, only the 1.16.5 version of Atum and curios is installed. I used the latest version of forge. Everything else works, but when I build a portal and enter, the game crashes. There are no other mods installed. I'll post the crashlog below:

[2021-05-12-1.log.gz](https://github.com/TeamMetallurgy/Atum2/files/6466304/2021-05-12-1.log.gz)
[debug-1.log.gz](https://github.com/TeamMetallurgy/Atum2/files/6466305/debug-1.log.gz)

**Comment by GirafiStudios** [comment]
The logs you're providing is only saying that you're missing Curios, or that the version you're using is an old version of Curios.
Potientially you might have accidently installed the Fabric version of Curios.

**Comment by GirafiStudios** [comment]
No worries, I was just very confused what you were talking about - based on the logs.
Somehow it's the CrashReport reporter itself that's crashing, rather than something in Atum.

Would you happen to use a cracked Minecraft account, or run your server in offline mode?

**Comment by GirafiStudios** [comment]
My only guess to what could be causing the issue, is that you're using a very old version of Java 8 (1.8.0_51). Try updating to the latest version of Java 8

**Comment by Himynameissomeone** [comment]
Just uninstalled and reinstalled java to the latest version on the internet. I'm sooo sorry for the inconvenience, but is it the same issue still?
[crash-2021-05-12_14.52.56-server.txt](https://github.com/TeamMetallurgy/Atum2/files/6468480/crash-2021-05-12_14.52.56-server.txt)

**Comment by GirafiStudios** [comment]
It is indeed the same crash.
You don't have your singleplayer world open to lan, right?
Also you're still using the same version of Java 8. Make sure to change it under Installations -> Select your instance -> More Options ->Change Java Executable to the version you just installed

**Comment by Himynameissomeone** [comment]
Currently, all other dimensions seem to work (including other mod dimensions). Just tried the same setup with twilight forest. (Atum/Curios/Twilight forest combination). The Nether/End/Twilight forest portal all work. Only when I enter Atum, the game crashes.
Also, I tried to change the Java version, but it got overly complicated and when I put: "C:\Program Files (x86)\Java\jre1.8.0_291\bin\javaw.exe" the game just crashes, so I've given up.
Have others successfully entered Atum? If so, this is probably my problem. However, other dimensions work so that may not be the case. Again, so sorry for the inconvenience- you shouldn't be fixing my problems. I can try to wait until newer versions of Atum comes out.

**Comment by GirafiStudios** [comment]
Yes, you're the only one with this problem somehow.
Could you try using another launcher, that's not the vanilla launcher?

**Comment by Himynameissomeone** [comment]
Yup just successfully ran minecraft on latest Java. I figured out how to do it. Yet it still crashes for some reason. Lan is also not on. Just commented if you might want to see the new crashlog. If you don't want to answer, feel free not to (it must be really annoying at this point). Thanks so much for all the help!
[crash-2021-05-12_17.43.13-server.txt](https://github.com/TeamMetallurgy/Atum2/files/6469221/crash-2021-05-12_17.43.13-server.txt)

**Comment by GirafiStudios** [comment]
Is it the same world you keep trying?

I said different launcher, not different Ja version this time.

**Comment by Himynameissomeone** [comment]
Some good news- I have successfully entered atum. It's just that it now freezes/crashes as soon as I enter it. And in new worlds, I'm getting the same issue. I'll post some crash reports. If this doesn't get solved here, I'll just go and install multimc. 
[crash-2021-05-12_19.23.45-server.txt](https://github.com/TeamMetallurgy/Atum2/files/6469545/crash-2021-05-12_19.23.45-server.txt)
[crash-2021-05-12_18.53.08-server.txt](https://github.com/TeamMetallurgy/Atum2/files/6469546/crash-2021-05-12_18.53.08-server.txt)
[crash-2021-05-12_19.37.13-server.txt](https://github.com/TeamMetallurgy/Atum2/files/6469548/crash-2021-05-12_19.37.13-server.txt)

**Comment by GirafiStudios** [comment]
Just tried with the vanilla launcher, so something seems to be up with your setup somehow.
The 2 first crashes, might be fixable on our end, i'll push a fix to Github.
The last one is still the same one.

**Comment by GirafiStudios** [comment]
Try this build here (Once it's done building): https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.16.5%20Jenkins/

**Comment by Himynameissomeone** [comment]
Just confirmed: MultiMC atum works flawlessly. Do most modded users use MultiMC? It's so much more convenient lol. The only thing is that it didn't transfer any of my prior data so I'll need to do some research to get that done. I'll try the vanilla tho.
After all this, I think the issue is a vanilla launcher exclusive problem. 
Thanks for all the help. I truly appreciate it!

**Comment by GirafiStudios** [comment]
Most people use the CurseForge launcher probably.
Glad it worked out!

I was unable to reproduce it on the vanilla launcher though, but my install was pretty much a fresh install. Only ever had 1.16.4 and a 1.17 snapshot installed before.

**Comment by sscards55** [comment]
I'm makings some assumptions here: somehow you managed to install forge twice on the same instance. I don't know if for has split it's universal and client jar but in the crash I saw that there were 2 different forge jars, 1 universal and one client.
