### ISSUE TITLE
Throwing quail eggs gives Take Aim arrrow advancement

### ISSUE THREAD

**Issue by TopPercentageRattata** [TeamMetallurgy/Atum2#234]
Throwing quail eggs gives take aim advancement.
Vanilla removed eggs giving the shooting arrows advancement back in 1.12( https://bugs.mojang.com/browse/MC-115880 ), so quail eggs should probably follow what regular eggs do and not give the arrow shooting advancement:.
Minecraft version: 1.16.5
Atum version: Atum-1.16.5-2.2.0

**Comment by GirafiStudios** [comment]
Unable to reproduce.
