### ISSUE TITLE
Water doesn't evaporate.   Even at Sand Plains

### ISSUE THREAD

**Issue by okitayuki0817** [TeamMetallurgy/Atum2#242]
![2021-05-15_03 24 53](https://user-images.githubusercontent.com/84203401/118319379-40c8f680-b52d-11eb-9fbb-d70ba8269653.png)
![2021-05-15_03 24 55](https://user-images.githubusercontent.com/84203401/118319383-41fa2380-b52d-11eb-90d7-7b41ee0db805.png)
1.16.5   Atum-1.16.5-2.2.2

**Comment by GirafiStudios** [comment]
That's an intended change in Atum 2.2, as mentioned in the huge changelog for version 2.2.0
