### ISSUE TITLE
Some artifacts don‘t lose durability in 1.16.5

### ISSUE THREAD

**Issue by rtxyd** [TeamMetallurgy/Atum2#244]
I just found this mod update to 1.16.5.
It seems some artifacts (nuits_vanishing, isis_healing, shus_swiftness) should have durability attribute  because they can be enchanted with "mending", "unbreaking", but they are not able to consum durability at any conditions. 
And when I play the mod on 1.12.2 they actually have a durability bar consumed when player trigger the features. Is this a update or bug somehow? 
It's not fair when I get a unbreakable "nuits_vannishing" and hit monster's with no movement because they can't see me.

**Comment by GirafiStudios** [comment]
It's an intended change, that they don't have durability anymore. It's a bug, that they can still get enchanted, thanks :)

**Comment by rtxyd** [comment]
@GirafiStudios Oh, I didn't know you reply so fast. By the way, can you reserve the durability attribute switch in config? It's just my own wish, I prefer items with durability to trigger my passion of adventure.

**Comment by GirafiStudios** [comment]
Unfortunately that's not possible, due to the order things are loaded as of 1.13.

**Comment by GirafiStudios** [comment]
Just tested. None of the amulets can be enchanted already.
