### ISSUE TITLE
Atum 2 Using Undergarden Mod Elements in Terrain Generation

### ISSUE THREAD

**Issue by CyberPunk2064** [TeamMetallurgy/Atum2#245]
Minecraft 1.16.5, Forge 36.1.0, Atum 2 version 2.2.2, The Undergarden 0.5.1

Atum 2 seems to be using Undergarden Frost Field biome elements (blocks, plants, ambient sounds, etc.) to form rivers. I tried this on two different seeds and it was the same. Just long, thin lines of snow and sand winding through the desert, immediately switching to creepy sounds.

**Comment by GirafiStudios** [comment]
Could you provide some screenshots?
Can't reproduce it.

**Comment by CyberPunk2064** [comment]
![scrnsht1](https://user-images.githubusercontent.com/71945705/118379994-5d544580-b5a4-11eb-938a-6191c36aa583.png)
![scrnsht2](https://user-images.githubusercontent.com/71945705/118379996-5decdc00-b5a4-11eb-898a-5d8b4ca48f3d.png)
![scrnsht3](https://user-images.githubusercontent.com/71945705/118379998-5f1e0900-b5a4-11eb-91dc-d4907dac3b44.png)
![scrnsht4](https://user-images.githubusercontent.com/71945705/118379999-5f1e0900-b5a4-11eb-9340-84f8736b682d.png)
![scrnsht5](https://user-images.githubusercontent.com/71945705/118380001-5fb69f80-b5a4-11eb-8cbf-c47443398fd3.png)

**Comment by GirafiStudios** [comment]
That's very weird.
I assume you have a bunch of mods installed?
Could you try with just Atum and Undergarden? (And Curios of course)

**Comment by CyberPunk2064** [comment]
Issue did not occur with only Atum, Undergarden, Curios, Xaero, and WAWLA installed.
<SPOCK EYEBROW>Fascinating. </SPOCK EYEBROW>

**Comment by CyberPunk2064** [comment]
Issue did not occur with only Atum, Undergarden, Curios, Xaero, and WAWLA installed.
\<SPOCK EYEBROW>Fascinating. </SPOCK EYEBROW>

**Comment by GirafiStudios** [comment]
That's very interesting.
Could you provide the list of mods, you originally used? Possibly a CurseForge export, if you have one.

**Comment by MokahTGS** [comment]
This happens when biomes conflict.  There is a mod that is messing up the biome tags.

**Comment by GirafiStudios** [comment]
Thank you for the clarification :)
As we do not use Biome Tags to control our generation at all, we can't do anything about it.

**Comment by MokahTGS** [comment]
I'd suggest this gets posted on the Undergarden github
