### ISSUE TITLE
Pyramids

### ISSUE THREAD

**Issue by TheWhale03** [TeamMetallurgy/Atum2#247]
when I got to two different pyramids the doors wouldn't open, do you know why?
![2021-05-15_17 49 35](https://user-images.githubusercontent.com/73250731/118380262-f6379080-b5a5-11eb-9e7f-4eb0dca73334.png)

**Comment by GirafiStudios** [comment]
Because it's not a door. Yet.
You need to place Nebu Torches on both blocks next to the "doors"
