### ISSUE TITLE
[1.16.5] Unregistered features reported by Blame mod

### ISSUE THREAD

**Issue by bessiq** [TeamMetallurgy/Atum2#252]
Forge: 36.1.23
Atum-1.16.5-2.2.3.jar
latest.log: https://gist.github.com/bessiq/7cbf9be1d8abe9a1c5923d94c4df2bfa

Hey,

Glad to see Atum on 1.16.5. Unfortunately, it seems to have a lot of unregistered features that are breaking features from other mods/datapacks. You can search the gist for Blame Report, or check the the summary of possible broken features on line 2898.

I removed all but a few client mods to be sure it wasn't a conflict with another worldgen mod. If you'd like more info, just let me know. Thanks.

**Comment by GirafiStudios** [comment]
Thanks for the report, I'll look into it.

**Comment by pm065** [comment]
TelepathicGrunt (Blame creator) has been robotically copy-pasting a message with more information about the bug on repos they have found to have unregistered features, an example of which can be found here: https://github.com/MapperTV/embellishcraft/issues/24 in case more info is needed (:

**Comment by bessiq** [comment]
> TelepathicGrunt (Blame creator) has been robotically copy-pasting a message with more information about the bug on repos they have found to have unregistered features, an example of which can be found here: https://github.com/MapperTV/embellishcraft/issues/24 in case more info is needed (:

Yes, I was honestly hoping/expecting TG to beat me here to report this. He is a machine. 🤖😋
