### ISSUE TITLE
Geb's Toil

### ISSUE THREAD

**Issue by alfieboris** [TeamMetallurgy/Atum2#253]
Geb's Toil is supposed to be unbreakable but it can lose durability.
![2021-05-21_15 13 30](https://user-images.githubusercontent.com/47575790/119143016-7008c780-ba47-11eb-9013-7f351fa79258.png)

**Comment by GirafiStudios** [comment]
What Atum version are you using?

**Comment by alfieboris** [comment]
The newest
Atum 1.16.5 - 2.2.3

**Comment by GirafiStudios** [comment]
Not sure where you got the idea that Geb's Toil should not take damage, nowhere does it say that.
Works as intended.

**Comment by alfieboris** [comment]
I think in the 1.12.2 version it didn't use any durability iirc and perhaps it was a bug. But either way I'm glad I now know that.
