### ISSUE TITLE
Tefnuts's call

### ISSUE THREAD

**Issue by alfieboris** [TeamMetallurgy/Atum2#254]
Tefnuts's call (when in 3rd person) is turned other way around and also its actual charging is longer than its animation (including the change of FOV)
![2021-05-21_15 12 47](https://user-images.githubusercontent.com/47575790/119143553-0341fd00-ba48-11eb-909f-031bdbd1680b.png)

**Comment by GirafiStudios** [comment]
Known issue. Unfortunately, that can't be fixed, since what allows for it to be done in vanilla is hardcoded.
