### ISSUE TITLE
Farmer villagers do not replant emmer

### ISSUE THREAD

**Issue by Jackiecrazy** [TeamMetallurgy/Atum2#258]
To date I have observed two unusual behaviors on Atum villagers. I may find (and update this post with) more in the future.
- farmers do not replant emmer.
- it doesn't seem possible to get trades from the curator.

**Comment by Jackiecrazy** [comment]
I see, it's like piglins! The other one still exists though.

**Comment by Jackiecrazy** [comment]
By the way, wolves don't have a sitting animation, making them hard to figure out, and palm fence gates aren't rendered slightly lower for walls.

**Comment by Jackiecrazy** [comment]
Farmers have a trade to convert 3 paper to 24 gold coins, and 1 coin to 20-some maps.

**Comment by sscards55** [comment]
Can you open a ticket for each individual issue please?

**Comment by GirafiStudios** [comment]
Another time that's preferred, yea.
But since he have already left the comments here, it's fine for this time.

**Comment by Jackiecrazy** [comment]
Oh, apologies, I forgot in my excitement.
