### ISSUE TITLE
[Suggestion] Godhammer being enchantable

### ISSUE THREAD

**Issue by alfieboris** [TeamMetallurgy/Atum2#263]
It would be nice if the hammer could be enchantable with, for example:

**Silk touch**
If you want to store the godforged blocks and don't want to break them, it would be nice if you place it by accident and want to pick it back up.

**+**

**!!!!!!!! don't if intended but the hammers are stackable up to 64 !!!!!!!!!!!**

**Comment by GirafiStudios** [comment]
You can pick Godforged Blocks up again with a pickaxe, just takes a while, no need for silk touch.
Hammers can stack up to 64, as they don't have durability.

**Comment by alfieboris** [comment]
ok thanks.
