### ISSUE TITLE
Portal mobs

### ISSUE THREAD

**Issue by sscards55** [TeamMetallurgy/Atum2#264]
It was recently brought to my attention that the reason mobs are not allowed to pass through portals is because they become invisible when traveling through. The solution to this should simply be to chunkload the other side of the portal as well. When a mobs is moved to a chunk that isn't loaded the game can "lose track" of the entity.

**Comment by GirafiStudios** [comment]
That was never a major reason why.
The main reason is balance, allowing for vanilla entities to enter Atum, would make especially the food situation in Atum a lot easier.
