### ISSUE TITLE
[suggestion] nerf Nuit's Vanishing slightly

### ISSUE THREAD

**Issue by Jackiecrazy** [TeamMetallurgy/Atum2#267]
As it is, the amulet is extremely powerful, as you can break aggro with most creatures by standing still or sneaking. It's possible to stand in a group of monsters and slowly kill all of them without any danger, trivializing even pharaohs and other powerful entities. To this end I have some possible ideas on nerfing it:
- Making it only work in darkness. It makes sense considering Nuit roughly corresponds to the nighttime sky. Perhaps each light level under 15 reduces detection range or chance (LivingVisibilityEvent can modify this) by 10%, so you cannot be seen at midnight, but during a daytime thunderstorm it'll only reduce detection range by 50%.
- Temporarily disable it on attack or being bumped into. The former turns the amulet into a tool to align yourself for the perfect initiative strike, and the latter would be the expected result of someone bumping into an invisible person.

**Comment by GirafiStudios** [comment]
Thank you for the suggestion(s).
I'm gonna look into something like the 2nd thing you suggested.
