### ISSUE TITLE
Atum portal keeps going still.

### ISSUE THREAD

**Issue by TheRanker** [TeamMetallurgy/Atum2#269]
Atum portal is growing each time using it. Even after the latest update that says fixes it is applied.  It actually got worst to be honest. It is now ~15 blocks high 
![unknown-11](https://user-images.githubusercontent.com/5889820/119276733-58237600-bbf6-11eb-84fe-cfa704b4a440.png)

**Comment by GirafiStudios** [comment]
What Atum 2 version are you using?

**Comment by TheRanker** [comment]
Atum-1.16.5-2.2.3

**Comment by GirafiStudios** [comment]
Nothing have changed with portals at all in the latest update (Or in any 1.16.5 update for that matter), so I have no clue what you're on about.

**Comment by TheRanker** [comment]
Atum 2  lastest update suppose to fix this bug. That's what I'm on about.

**Comment by GirafiStudios** [comment]
No it was not? Where did you get that from?

**Comment by TheRanker** [comment]
Fixed Tomb generation issues (NOT!)
- Fixed Hoppers insertion issues, with Kilns
- Fixed Artifact Armor toughness tooltip issue

**Comment by TheRanker** [comment]
FFS.  Tomb not portal.   FFS. Sorry.  So he generation of the portal isn't fixable? When will it stop? Y-255?

**Comment by GirafiStudios** [comment]
You're being rude and dumbass, so I'm closing this.
Tombs has nothing to do with the portals..
