### ISSUE TITLE
[suggestion] change shu's breath

### ISSUE THREAD

**Issue by alfieboris** [TeamMetallurgy/Atum2#270]
Maybe a nice change to the bow would be instead of faster charging (because it isn't faster, because of the charging bug which is the same with tefnuts's call) the arrow could have (when fully charged) higher velocity but it still would be affected by gravity so it wouldn't be the same as horus's soaring.

**Comment by GirafiStudios** [comment]
Fixed the charging issue, rather than changing behaviour.
