### ISSUE TITLE
Breaking limestone slab drops nothing

### ISSUE THREAD

**Issue by mnsnownutt** [TeamMetallurgy/Atum2#271]
Forge 36.1.0
MC 1.16.5
Atum 2 1.16.5-2.2.3

Assume it is a loot table issue, but when you break a limestone slab, it does not drop anything.

**Comment by GirafiStudios** [comment]
Solved by https://github.com/TeamMetallurgy/Atum2/commit/4ccfe48fa92568e0d5e2e31a0f5d858d52124bd8
(Accidently typed in the wrong number)
