### ISSUE TITLE
Pharaoh Pra’darech VII is much stronger

### ISSUE THREAD

**Issue by BarionLP** [TeamMetallurgy/Atum2#272]
I think the title says everything...
Pharaoh Pra’darech VII is much stronger than the others pharaohs. We (4 Players) died against him several times. The others were easy.
is this wanted?

**Comment by Shadowclaimer** [comment]
The Pharaohs have randomized names.

What color were they?

**Comment by BarionLP** [comment]
Bown i think

**Comment by GirafiStudios** [comment]
The Pharaoh's have different abilities, depending on which God they follow.
Some are more difficult than others.
