### ISSUE TITLE
Crash in Atum dimension

### ISSUE THREAD

**Issue by DcNdrew** [TeamMetallurgy/Atum2#273]
Hi! I don't know what can cause this, but here is the crash:
https://paste.ee/p/zGSxg

**Comment by sscards55** [comment]
The issue appears to be an incompatibility with Enhanced Animals. Please report it in their issue tracker as well.

**Comment by DcNdrew** [comment]
Well, there is an opened issue already. :)
https://github.com/SaemonMoki/ExtendedAnimals/issues/76
