### ISSUE TITLE
NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by judicius** [TeamMetallurgy/Atum2#275]
Forge: 36.1.24
MC 1.16.5
Atum 2.2.4

I've seen this reported a few times where there were always other mods causing some issues but i'm able to duplicate with just Atum installed.

I have all 13 job blocks in a creative flat world, I spawn in 15 Atum villagers with no issue. When I spawn in vanilla villagers the game crashes. 

I've been able to duplicate multiple times.

https://gist.github.com/judicius/8a97bd9a3c45a2bc1e632dca60ee7a0c

**Comment by sscards55** [comment]
Can you try this build to see if it still occurs?
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.16.5%20Jenkins/

**Comment by judicius** [comment]
I'm not so sure. I can't seem to duplicate on that build. I'll keep trying and update if I can cause a crash.

**Comment by sscards55** [comment]
That's very interesting, I wonder what exactly changed.

**Comment by judicius** [comment]
not sure maybe the null to none was the cause of the issue. Are you pushing that build as a hotfix?

**Comment by GirafiStudios** [comment]
Since sscards edited his message, your response is a bit confusing.
Are you saying that the issue happens on Atum 2.2.4, but not the latest jenkins build?

**Comment by sscards55** [comment]
My bad, it's the latest Jenkins build.

**Comment by GirafiStudios** [comment]
So it´s happening on the latest Jenkins build, but not for 2.2.4?

**Comment by judicius** [comment]
it's happening on 2.2.4, the current released version but, not on the jenkins build I was linked. At least I've been unable to duplicate on the jenkins build.

**Comment by GirafiStudios** [comment]
Oh okay, perfect!
I´ll consider this fixed then. Hopefully I get a new release out in a day or two.
