### ISSUE TITLE
Failing to place Player in existing portal, resulting in creation of new portal instead

### ISSUE THREAD

**Issue by AllThatJazz139** [TeamMetallurgy/Atum2#276]
Seemingly randomly a new Atum portal spawns on top of the previous one.
Atum 2 1.16.5 version ~~10.1.2~~ 2.2.4 
![image](https://user-images.githubusercontent.com/77024394/120383069-3fdbe700-c2d9-11eb-8eb2-91498a9e707f.png)

**Comment by GirafiStudios** [comment]
We have no version called 10.1.2.
Could you try again?

**Comment by AllThatJazz139** [comment]
Sorry, must have misread another mod's version number somehow. I meant 2.2.4

**Comment by GirafiStudios** [comment]
Is this on a server, or a singleplayer world?
And could you provide a mod list, preferably a mod list or a modpack.

**Comment by AllThatJazz139** [comment]
Yes, This is on a server.
And here is my modpack's curseforge page dependency list that shows all the mods contained in it.
https://www.curseforge.com/minecraft/modpacks/nerd-herd-modpack-season-4/relations/dependencies

**Comment by GirafiStudios** [comment]
Is the server running some sort of Forge/Bukkit hybrid, or just straight up Forge?

**Comment by AllThatJazz139** [comment]
Sorry for not including this in the original post, It is an unmodified Forge installation of version 36.1.23.

**Comment by GirafiStudios** [comment]
There are a feww Forge/Bukkit hybrids for 1.16.5. I forget their names though.
But thanks for the update, I´ll look into it when I get a chance.

**Comment by officialjrem** [comment]
I am having this same issue every other time I go into atum it spawns a new portal on top the old one in both the overworld and atum itself

**Comment by GirafiStudios** [comment]
Can you reproduce this in singleplayer, or does it only happen on a server?

**Comment by AllThatJazz139** [comment]
Seemingly not no. Unless there is some other aspect from another mod that is causing it by bring ing something through the portal with me then it doesn't happen in single player no.

**Comment by officialjrem** [comment]
This is happening to me in single player.

**Comment by Darkest-Traveler** [comment]
I have the same issue on multiplayer. Does not happen in the same pack on single player.
Here is my modlist: https://pastebin.com/QJZJfDE7 some of the mods are similar as the person reporting.
I'm running a Forge 36.1.0, 1.16.5 server Atum 2.2.4

**Comment by Darkest-Traveler** [comment]
Update (we talked in discord).  I'm having issues right now related to the mod BG core with entity duplication, generating extra nbt tag info and it removing or messing with tile entities, it even has completely destroyed the ocean monument generation on my server world. So it might be causing the duplication issue with the portals both myself and the op have that mod. Hopefully this helps.

**Comment by AllThatJazz139** [comment]
Hm... That might also explain why Mowzie's Mob's Bosses have been duplicating as well...

**Comment by GirafiStudios** [comment]
> Hm... That might also explain why Mowzie's Mob's Bosses have been duplicating as well...

If you could test this without BG Core, that would be much appreciated :)

**Comment by scotty2** [comment]
I have this problem in single player. No BG Core. Valhelsia 3 mod pack, though.
I added some debug logging, and it appears that the portal generation is failing to find the existing portal in the dimension you travel to (This will duplicate sometimes when going into Atum, and sometimes when coming back from it)
Maybe something to do with the chunk loading of the destination dimension?

**Comment by WanderingAlchemist** [comment]
For what it is worth I have had this issue on a server and a similar issue occurs with The Undergrowth except that the undergrowth portal spawns in more random but nearby spots while the Atum portal is always one over and up. Also whenever this occurs you will get the same thing on the return trip but the duplication doesn't happen again after that until (unconfirmed) a server restart.

**Comment by Greatone123** [comment]
I'm also having this issue on my server, doesn't happen all the time, but if you need any I fo I'm glad to throw it out there.

**Comment by GirafiStudios** [comment]
Unable to recreate in newer versions.
