### ISSUE TITLE
Arrow texture bugs

### ISSUE THREAD

**Issue by sscards55** [TeamMetallurgy/Atum2#280]
Some of the arrow entity textures are not aligned properly some are too low and some too high.

**Comment by Shadowclaimer** [comment]
Can you provide evidence of this? I'm not really sure how to check this.

**Comment by sscards55** [comment]
Also tefnut's rain, shu's breath, and horus' soaring, all have the arrow lower in their second frame of charge.

**Comment by sscards55** [comment]
![2021-06-07_07 34 30](https://user-images.githubusercontent.com/5591207/120979001-a3946300-c764-11eb-8890-26e71b1d5351.png)
![2021-06-07_07 35 27](https://user-images.githubusercontent.com/5591207/120979003-a42cf980-c764-11eb-96cc-53e409cf5b80.png)
![2021-06-07_07 37 08](https://user-images.githubusercontent.com/5591207/120979006-a4c59000-c764-11eb-83aa-2751edde138c.png)
![2021-06-07_07 38 23](https://user-images.githubusercontent.com/5591207/120979007-a4c59000-c764-11eb-8f7d-8b97df1b9301.png)
![2021-06-07_07 39 38](https://user-images.githubusercontent.com/5591207/120979010-a55e2680-c764-11eb-924f-dd41080950ae.png)
![2021-06-07_07 40 21](https://user-images.githubusercontent.com/5591207/120979011-a55e2680-c764-11eb-8a7f-eb70f9e461fb.png)
![2021-06-07_07 41 34](https://user-images.githubusercontent.com/5591207/120979013-a55e2680-c764-11eb-9ba7-3b8a04fb2475.png)

**Comment by GirafiStudios** [comment]
That's not how I understood the issue to begin with. I thought it was the arrow entity textures, that had an issue.

**Comment by sscards55** [comment]
No the rendering is fine, it's just that the textures themselves are not aligned properly.

**Comment by GirafiStudios** [comment]
Which is the bow texture, not the arrow texture :)

**Comment by sscards55** [comment]
I should clarify, the arrow texture on the entity is what this issue is about, I just brought up the bow texture as well.
I should probably just open up a new issue.

**Comment by GirafiStudios** [comment]
So if I understand correctly, you're saying that it's a problem that the arrow hits different places on the block, when aiming in the same location?
That's just how arrows work, also in vanilla. There is a bit of randomization to the firing of the arrow.

**Comment by sscards55** [comment]
No, the entity and the texture are rendered in the correct locations. The texture files are just not aligned properly, which causes the arrow to be rendered incorrectly.

**Comment by GirafiStudios** [comment]
Could you provide a comparison picture, that shows it?

**Comment by sscards55** [comment]
![Uploading Arrows.png…]()

**Comment by GirafiStudios** [comment]
I really don't see the issue.
Can you see something in the texture files?

**Comment by sscards55** [comment]
![ImageGlass_bFuNtuDBBT](https://user-images.githubusercontent.com/5591207/121187765-ef740480-c857-11eb-97a1-c047af21d668.png)
![ImageGlass_qWvkSqc6kd](https://user-images.githubusercontent.com/5591207/121187773-f0a53180-c857-11eb-97d2-c87d2d1036e7.png)
![ImageGlass_yB00MUMWwr](https://user-images.githubusercontent.com/5591207/121187778-f1d65e80-c857-11eb-922b-62d87fa6c28d.png)
![ImageGlass_TYqBdaBSJa](https://user-images.githubusercontent.com/5591207/121187789-f3a02200-c857-11eb-95e0-175e2b4ba894.png)
![ImageGlass_EeBmIFZsB8](https://user-images.githubusercontent.com/5591207/121187794-f438b880-c857-11eb-94e1-197aade0c598.png)

**Comment by GirafiStudios** [comment]
Oh you meant the tail of the arrows!
That's very minor. Something we'll look into for a future patch. It'll be put on the list :)

**Comment by sscards55** [comment]
it's not just the tail, it's the whole texture.
