### ISSUE TITLE
Tefnut's Rain arrow

### ISSUE THREAD

**Issue by sscards55** [TeamMetallurgy/Atum2#286]
Tefnut's Rain creative arrows are able to be picked up.

**Comment by sscards55** [comment]
![Q9SffTlrFS](https://user-images.githubusercontent.com/5591207/121173793-bb451780-c848-11eb-8b58-d2d6250cbf0a.gif)

**Comment by GirafiStudios** [comment]
Intended. Workaround to make it work properly in survival.
