### ISSUE TITLE
Oasis Biomes not generating 

### ISSUE THREAD

**Issue by RealCornQueen** [TeamMetallurgy/Atum2#289]
In my Atum 2 dimension, neither of the Oasis biomes have generated, using /locatebiome does nothing. Making a new world does nothing either. Any ideas?

**Comment by sscards55** [comment]
Is this on a server? Is it on a client? Do you have other mods installed? What version of the mod are you using? What version of minecraft are you using? What version of forge do you have installed?

**Comment by RealCornQueen** [comment]
I have 1.16.5 and its in my single player world I have the 2nd newest version of the atum. I am using some other mods. Is there any that have been known to cause issues?

**Comment by Shadowclaimer** [comment]
They spawn fine on our end so it has to be another mod you have installed.
