### ISSUE TITLE
Dust Wastelands biome from 'Better End Forge' are generating on the Atum

### ISSUE THREAD

**Issue by Brun333rp** [TeamMetallurgy/Atum2#290]
For some reason, Dust Wastelands from Better End Forge are generating in the Atum dimension. Note that it has a river-like shape, so this was probably meant to be a Dried River biome instead, wich is highly probable because when I type the command /locatebiome atum:dried_river it says that no biome of this type was found. I don't know what is the cause of this, but this is weird.

![image](https://user-images.githubusercontent.com/77504298/122624682-d2211080-d077-11eb-9e22-bec8dd43879d.png)

**Comment by GirafiStudios** [comment]
What version of Atum, was this world created on?

**Comment by Brun333rp** [comment]
I've installed the most recent version, but I don't know the version number specifically. gonna see this tomorrow, I'm tired now because I've been working on translating the mod and it took me a lot of time.

**Comment by Brun333rp** [comment]
Beethoven92/BetterEndForge#144 (I think that's how you mention a issue from other repository, idk)

**Comment by Brun333rp** [comment]
about the version number, I checker this now and it's 1.16.5-2.2.5

**Comment by GirafiStudios** [comment]
Could you provide a full list of your mods?

**Comment by Brun333rp** [comment]
Atum, Better End Forge, Optifine, Just Enough Items (JEI), Patchouli, and Curios API. some of these mods I no longer have installed (including Better End), but they were all installed when that happened.

**Comment by GirafiStudios** [comment]
Unable to reproduce with the mods listed. Please provide a test case, there is can be reproduce.
Would you have heppend to have removed biome/worldgen mods, after starting your world? That can cause this issue :)

**Comment by Brun333rp** [comment]
no, I didn't had other worldgen mods prior to that. and not being able to reproduce this issue is enough to close that? maybe I had some other mod that I don't remember, but that's very unlikely.

**Comment by Brun333rp** [comment]
> there is can be reproduce.

excuse me, what does that means?

**Comment by GirafiStudios** [comment]
That can be reproduced, is what I meant :) Typed it a little fast.
If there is no way for me to reproduce it, there is no way for me to even start attempting to fix it.

The issue is replaced to biome shifting, which is caused by removing mods most of the time.

Also mentioned here in one of BetterEnds issues: https://github.com/Beethoven92/BetterEndForge/issues/117

**Comment by Brun333rp** [comment]
oh, seeing that now I think that this issue here can be kept as closed. afterall there's probably not much thing you can do if it's a issue of Forge and not yours
