### ISSUE TITLE
Atum hostile mobs completely ignore Atum villagers, despite they targeting bandits

### ISSUE THREAD

**Issue by Brun333rp** [TeamMetallurgy/Atum2#291]
Atum monsters, despite attacking bandits and related mobs, do not care about Atum villagers, despite they visibly being humans, just like bandits. At least the undead ones should target them just like they do with bandits (mummies, forsakens, bonestorms and wraiths), and maybe even the ones outside Atum (zombies, husks, drowned, zombie villagers, skeletons, wither skeletons and strays).

**Comment by GirafiStudios** [comment]
Intended.

**Comment by Brun333rp** [comment]
why?

**Comment by Brun333rp** [comment]
why it's intended? is there some logic or even lore behind this?

**Comment by Shadowclaimer** [comment]
Because Atum has so many hostile mobs it would mean every village would be desolate.

At a later date the villages are getting guards which will allow us to introduce factional hostility, but for now they just ignore each-other for gameplay purposes.

**Comment by Brun333rp** [comment]
oh, that's understandable then 😄😅

**Comment by Brun333rp** [comment]
I guess then that the only reason they attack bandits is because they respawn overtime and are abundant

**Comment by Shadowclaimer** [comment]
Yea its a holdover from before Bandits were in patrols, it was meant to be a "flip" where when day comes all the night mobs are killed and vice versa.
