### ISSUE TITLE
Atum spawning Origins having issues respawning in the Atum

### ISSUE THREAD

**Issue by Darkmega18** [TeamMetallurgy/Atum2#292]
A cross post of this:
https://github.com/EdwinMindcraft/origins-architectury/issues/34#issue-925962085

Minecraft: 1.16.5
Origins forge: Origins-1.16.5-0.7.3.5-forge
Forge: 36.1.24
Atum: Atum-1.16.5-2.2.5
_[and many other mods...]_

But I've made a couple of custom origins in origins forge that spawn directly in the atum naturally. But I'm having a weird issue that makes them unable to respawn on death 90% of the time. 

I hit respawn but no error appears in console, no crash. Just a respawn button clicks in, then unclicks. When I try to exist to title I get an infinite dirt screen telling me it's saving game. and on end process and reload I'm still dead.

Although just now I managed to get one of my worlds to respawn luckily after waiting a while after a force restart of MC. I'm not sure what could cause it and what caused it to suddenly loosen up for me.

I don't wish to use the everyone spawns originally in Atum config option. I only want it for those it makes sense for. Could it be weird world loading or spawn condition issues?

**Comment by GirafiStudios** [comment]
Seems to be something they have to figure out on their end, with how to load Forge dimensions, before doing whatever they need to do.
Nothing that can be done on our end.
