### ISSUE TITLE
Tefnut's Call Glitched in Curio's

### ISSUE THREAD

**Issue by CacoVil08** [TeamMetallurgy/Atum2#293]
Atum 2 Version: 1.16.5 - 2.2.5

When you put a "Tefnut's Call" inside any Curio, the Texture inside the Curio is the Entity, not the Item... So... The Tefnut's Call just goes through the Curio.

(Ps: Idk how to send prints, im new in Github)

**Comment by sscards55** [comment]
You can just drop the picture in the textbox.

**Comment by CacoVil08** [comment]
Thx

**Comment by GirafiStudios** [comment]
Tefnut´s Call can´t go in any Curio slot. If it can, some other mod must be messing with the Curio slots.
