### ISSUE TITLE
[1.16.5] CraftTweaker can't resolve methods

### ISSUE THREAD

**Issue by ZigTheHedge** [TeamMetallurgy/Atum2#294]
These statements in script 
```
mods.atum.Quern.removeRecipeByOutput(<item:atum:emmer_flour>);
mods.atum.Quern.addRecipe(<item:atum:fertile_soil>, <item:atum:fertile_soil_pile>, 3);
```
fails. Both producing "No compatible methods found".
Minecraft: 1.16.5
Atum: 2.2.5
CraftTweaker: 7.1.0.314
Forge: 36.1.32

**Comment by sscards55** [comment]
You should not have "item:" in the script. just "<atum:emmer_flour>"

**Comment by ZigTheHedge** [comment]
@sscards55 unfortunately, no. Now the error tells me: "Invalid bracket exception: no prefix atum". And that shouldn't be case anyway, because all of my other scripts works fine with prefix (and they should).

**Comment by sscards55** [comment]
Never mind ignore what I said.

**Comment by GirafiStudios** [comment]
I´ve not updated the documentation on the wiki.
Should be like:
<recipetype:atum:quern>.removeRecipeByOutput(<item:atum:emmer_flour>);
<recipetype:atum:quern>.addRecipe(<item:atum:fertile_soil>, <item:atum:fertile_soil_pile>, 3);
