### ISSUE TITLE
Strange crash with chunk generation.

### ISSUE THREAD

**Issue by Chococrispii** [TeamMetallurgy/Atum2#295]
When approaching Pyramid structures (may be coincidental), game crashes with the description of "exception generating new chunk". [
[crash-2021-06-24_11.52.35-server.txt](https://github.com/TeamMetallurgy/Atum2/files/6710595/crash-2021-06-24_11.52.35-server.txt)
](url)

**Comment by GirafiStudios** [comment]
Some mod adding biomes, is not registering their biomes correctly, causing this issue.
Not Biomes O´Plenty, as I know that works for sure.
