### ISSUE TITLE
Kiln causes lighting glitch

### ISSUE THREAD

**Issue by thelovedolphin** [TeamMetallurgy/Atum2#296]
Having a kiln placed causes the chunk containing it to lose all light (not immediately, I'm not sure what causes it or how long it takes). Mobs can then spawn, even with light sources nearby. Blocks say light level 0

**Comment by sscards55** [comment]
What version of MC, Forge, and Atum are you using? Are you using amodpack? If not can you provide a list of mods.

**Comment by thelovedolphin** [comment]
Mc 1.16.5, forge 36.1.0, atum-1.16.5-2.2.4
Atum
Betterendforge
Betterstrongholds
Biomesoplenty
Create
Immersive portals
Xaerosworldmap
Chunkpregen
Curiosforge
JEI
Patchouli
Randomblockplacement
Yungsapi
