### ISSUE TITLE
[1.16.5] Sleeping in Atum doesn't skip the night

### ISSUE THREAD

**Issue by ZigTheHedge** [TeamMetallurgy/Atum2#297]
There was a similar issue in 1.12.2 version, but in 1.16.5, you can lay on a bed and... Nothing happens. You're just laying.
Minecraft: 1.16.5
Forge: 36.1.32
Atum: 2.2.5

**Comment by GirafiStudios** [comment]
Do you have Morpheus installed?

**Comment by ZigTheHedge** [comment]
Nope

**Comment by Gattoartico** [comment]
I actually had this issue on my server as well, wasn’t sure if it was Morpheus or not. I was gonna check but I haven’t had the time to do that yet

**Comment by ZigTheHedge** [comment]
I'm in a single-player world if it matters...

**Comment by Azuriuz** [comment]
iirc wasn't this an issue that could never be fixed because mojang didn't code dimensions with night/day in mind? Like, other dimension mods just don't even have a time of day, usually just night, or just day, or just sunset etc.
Maybe this got fixed in the new version but I know in the 1.12 version it wasn't fixable

**Comment by GirafiStudios** [comment]
> iirc wasn't this an issue that could never be fixed because mojang didn't code dimensions with night/day in mind? Like, other dimension mods just don't even have a time of day, usually just night, or just day, or just sunset etc.
> Maybe this got fixed in the new version but I know in the 1.12 version it wasn't fixable

I got it fixed on 1.15.2 & made it work with Morpheus.
Not sure what broke in 1.16, I´ll have to look into it.

**Comment by GirafiStudios** [comment]
Just tested, work fine with just Atum.
You probably have Quark installed, which breaks sleeping in any dimension, that´s not the Overworld. Please disable Quark´s "Improved Sleeping" in their config.

**Comment by ZigTheHedge** [comment]
That worked! Thank you!
