### ISSUE TITLE
Several gold related items are not on piglin_loved tag

### ISSUE THREAD

**Issue by Brun333rp** [TeamMetallurgy/Atum2#298]
This affects:

- Golden Desert Armor set;
- Golden Camel Armor;
- Golden Desert Wolf armor;
- Glistering Date;
- Golden Date;
- Enchanted Golden Date;
- Scarab (Item);
- Crunchy Golden Scarab;
- Gold Coin;
- All Artifacts (not counting the silver and dusty ones);

**Comment by GirafiStudios** [comment]
Added the majority of the suggestions, except Scarabs & the artifacts. Artifacts are all made out of Nebu, and should therefor not be added in "piglin_loved", as they like gold.

**Comment by Brun333rp** [comment]
ok, appart from the naming saying otherwise, it makes sense for them not being included. but then gold coins are not included as well, right? because they also seem to be made of nebu
