### ISSUE TITLE
Mobs spawning in the oasis and around mega torches

### ISSUE THREAD

**Issue by GeshaPruchkata** [TeamMetallurgy/Atum2#299]
Any types of mobs that attack me spawn  in the oasis near my villige,also spawn in places where I torched a lot.
Using Tlauncher
1.16.5-forge-36.1.0
Mods: Atum 2 (1.16.5-2.2.5)
Just Enough Items 7.7.0.106
Curios Api 1.16.5-4.0.5.1

**Comment by GirafiStudios** [comment]
We don´t offer support for anybody using Tlauncher.
