### ISSUE TITLE
Thoth's Direction

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum2#30]
![thoths_direction](https://user-images.githubusercontent.com/2214143/40382815-548d07d4-5dcd-11e8-8086-afcbc88981b5.png)

Effect:

"Guidance" "Guides you to the nearest treasure."

Compass that points towards the nearest ruin chest or pharaoh chest.

Will be gifted to the player as part of the later story events. DOES NOT DROP!

**Comment by GirafiStudios** [comment]
Closed by https://github.com/TeamMetallurgy/Atum2/commit/3c84fc18636d204208495d0e3fa3ffa48743989c
