### ISSUE TITLE
[1.16.5] Teleport to Overworld on death if bed is broken

### ISSUE THREAD

**Issue by ZigTheHedge** [TeamMetallurgy/Atum2#301]
My modpack is based on Atum as a home dimension. Players start in it and survive without a possibility of leaving. If player sets his spawn via Bed and the Bed becomes obstructed, player will respawn in the Overworld on death.
Is it possible to fix?

**Comment by GirafiStudios** [comment]
Is the "Start in Atum" config option set to true?

**Comment by ZigTheHedge** [comment]
Yes
