### ISSUE TITLE
[1.16.5] Acacia saplings doesn’t grow

### ISSUE THREAD

**Issue by ZigTheHedge** [TeamMetallurgy/Atum2#302]
Is it supposed to be like that? You can find spawned Acacia trees in oasis, get its saplings and plant it on a Fertile Soil, but it will never grow up.

**Comment by ZigTheHedge** [comment]
And if you managed to place vanilla dirt in world (using /setblock for example), it will grow on it normally.

**Comment by GirafiStudios** [comment]
Unfortunately to how vanilla saplings are coded, and how Forge changes things, this is not possible to fix.
