### ISSUE TITLE
Chunk Generation Fail - Server Crash

### ISSUE THREAD

**Issue by kriz18** [TeamMetallurgy/Atum2#306]
Everytime you enter the portal the server would crash with error message: "io.netty.channel.abstractchannel$annotatedconnectexception:connection refused: no further information:"

Turns out the Dimension fails to generate the chunks and whoever jumped into the portal would be in a constant logout/login loop and would crash the server (had to reset the player data and lost everything).

Please can you look into this.

Thanks.

**Comment by GirafiStudios** [comment]
Please provide your latest log and your debug log.

**Comment by kriz18** [comment]
[latest.log](https://github.com/TeamMetallurgy/Atum2/files/6769122/latest.log)

**Comment by GirafiStudios** [comment]
Shows nothing unfortunately. Could you provide your debug log too, and the server logs?

**Comment by kriz18** [comment]
this one is included with the Better Minecraft Plus modpack, does that have to do with anything? i'l try and run the debug command while playing and provide you the report after.

**Comment by kriz18** [comment]
[latest.log](https://github.com/TeamMetallurgy/Atum2/files/6788914/latest.log)
[Atum Dimension Crash Log 09.07.21.txt](https://github.com/TeamMetallurgy/Atum2/files/6788915/Atum.Dimension.Crash.Log.09.07.21.txt)

Hello, here's the latest crash report

**Comment by GirafiStudios** [comment]
Will get fixed by the PR mentioned here https://github.com/TeamMetallurgy/Atum2/issues/311

**Comment by GirafiStudios** [comment]
Fixed by https://github.com/TeamMetallurgy/Atum2/commit/bb61b74c4f60d675486cf88792372dc4ed9f587c
