### ISSUE TITLE
Ruin18 NBT Crash with v2.2.5

### ISSUE THREAD

**Issue by SigynLaufeyson** [TeamMetallurgy/Atum2#307]
I'm running version 2.2.5 and it keeps crashing.  The log file / Blame report says:

 _Failed to load structure nbt file from:  atum:ruins/ruin18
 The path represented by this is:  data/atum/structures/ruins/ruin18.nbt
 Most common cause is that there is a typo in this path to the nbt file.
 Please let the mod author know about this so they can double check to make sure the path is correct.
 A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder._

Let me know if you need my full debug log or crash report

**Comment by GirafiStudios** [comment]
There is no ruin 18. You most likely have an old config. Change the ruin amount to 17 in the config, or delete the config to let it generate a new (If you haven´t made any changes yourself)
