### ISSUE TITLE
Lighthouses do not generate in Valhelsia 3 Modpack

### ISSUE THREAD

**Issue by Glenn-v-W** [TeamMetallurgy/Atum2#310]
Playing on a server in the Valhelsia 3 modpack, with Atum-1.16.5-2.2.5, we have explored a very large area, and are very confident that no lighthouses have generated.

Are we missing a config setting on the server to enable them? Is there NBT data we could use to spawn one manually?

Any help would be greatly appreciated!

**Comment by GirafiStudios** [comment]
That´s because there is no Lighthouse in Atum 2.2.0+, as it states in the changelog for Atum 2.2.0 :)
