### ISSUE TITLE
Rap's Step + Blue skies dimension crash

### ISSUE THREAD

**Issue by Daejangnamu** [TeamMetallurgy/Atum2#312]
Client crashes when walking on blue skies dimension lava with Ra's Step ring equipped.

Blue Skies: https://www.curseforge.com/minecraft/mc-mods/blue-skies/files/3385608

[crash-2021-07-14_02.38.04-server.txt](https://github.com/TeamMetallurgy/Atum2/files/6811080/crash-2021-07-14_02.38.04-server.txt)

![123213](https://user-images.githubusercontent.com/52635462/125504349-2716182f-dc13-4ba2-ba70-aa1718f1c22c.png)

**Comment by sscards55** [comment]
This is the fault of blue skies for tagging non fluid blocks as fluids. I have already commented on their issue tracker.

**Comment by sscards55** [comment]
Actually it is kind of atum's fault, I checked the code a bit more carefully and it turns out that any block can return any fluid, which makes it a bit of no ones fault.

**Comment by Jonathing** [comment]
There's a method that gets the Optional<T> property value, if that helps. That way it also accounts for other blocks that might do something similar to what we did.
