### ISSUE TITLE
Enchanted Forest (BYG) Biom generates in Atum2 Dimension

### ISSUE THREAD

**Issue by DerShiho** [TeamMetallurgy/Atum2#314]
Like the title indicates, the Enchanted Forest Biom from "Oh the Bioms you will go" (BYG) generates in Atum2 on top of Sand Dunes Biom. 
![Screenshot 2021-07-17 022825](https://user-images.githubusercontent.com/87499385/126020056-58f6f10c-5d90-449a-acb1-84f5c34da53f.png)

![Screenshot 2021-07-17 023450](https://user-images.githubusercontent.com/87499385/126020059-f0722630-5f2c-4185-b9e5-4f7217dbd6e5.png)

Map View:
![Screenshot 2021-07-17 022903](https://user-images.githubusercontent.com/87499385/126020058-9a1339dd-3bef-4c12-bd28-d42d2861b973.png)

I use the Latest Forge in MC 1.16.5
Atum 2
BYG
Terraforged
All on their latest version.

**Comment by Brun333rp** [comment]
I had a similar issue with Better End Forge, where the Dust Wasteland biome replaced Dried River biomes. but it has been closed because there wasn't much that could be done about it, though it might be different this time

**Comment by GirafiStudios** [comment]
Could you try installing Blame? It´s a mod that checks if mods are not registering their ConfiguredFeatures. Atum is doing this correctly, as of version 2.2.4

Download here: https://www.curseforge.com/minecraft/mc-mods/blame

**Comment by GirafiStudios** [comment]
Should be fixed by https://github.com/TeamMetallurgy/Atum2/commit/bb61b74c4f60d675486cf88792372dc4ed9f587c
