### ISSUE TITLE
[Bug?] Curator villagers pick up just about anything when throw it, and can't take items directly to appraise.

### ISSUE THREAD

**Issue by Darkmega18** [TeamMetallurgy/Atum2#316]
Silly stuff.
https://www.youtube.com/watch?v=M4GLXPJysXQ

1. Can't take items directly from you. must toss it. :V
2. will go for and pick up just about anything on the floor. including weapons and other things they shouldn't trade and not give you anything for them.

Yes there are a lot of other mods.
Atum: 2.2.5
Forge: 36.1.62

**Comment by Darkmega18** [comment]
well ok. hope the video was silly enough.

**Comment by GirafiStudios** [comment]
Yea, it was :) Was helpful to determine that it was anything they would pick up - not just weapons and similiar.
In case it wasn´t clear, the issue got fixed.

**Comment by Darkmega18** [comment]
> 
> 
> Yea, it was :) Was helpful to determine that it was anything they would pick up - not just weapons and similiar.
> In case it wasn´t clear, the issue got fixed.

yes indeed. just hoping for an eventual release for all the bugs you've fixed lately. :)

**Comment by GirafiStudios** [comment]
Most likely later today :)

**Comment by Darkmega18** [comment]
https://media.tenor.co/videos/5b9a660779837b9aa0cb822ef116a306/mp4
