### ISSUE TITLE
Crash in Atum - atum.world.biome.AtumBiomeProvider

### ISSUE THREAD

**Issue by SharkieTV** [TeamMetallurgy/Atum2#318]
Only a few of my Players are experiencing a Crash in your Dimension. Sorry if this is a Duplicate.

[Crash](https://pastebin.com/rmDJkJYs)
[Latest.log](https://cdn.discordapp.com/attachments/869767317410701314/869858893164077088/latest.log)
[Modpack](https://www.curseforge.com/minecraft/modpacks/better-mc-plus)

**Comment by sscards55** [comment]
duplicate of #295

**Comment by sscards55** [comment]
A mod is adding biomes and not registering them correctly.
