### ISSUE TITLE
CraftTweaker Interaction

### ISSUE THREAD

**Issue by gwydion0917** [TeamMetallurgy/Atum2#324]
With just CraftTweaker, Atum and Curios API installed, Strange Sand always smelts as MC Glass instead of Atum Crystal Glass.

**Comment by GirafiStudios** [comment]
Can confirm this happens with CraftTweaker installed. Will look into it.

**Comment by GirafiStudios** [comment]
Workaround can be grabbed on Jenkins, until next release: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.16.5%20Jenkins/277/
