### ISSUE TITLE
Overspawn of mobs in Atum dimension

### ISSUE THREAD

**Issue by Hiranus** [TeamMetallurgy/Atum2#327]
![obraz](https://user-images.githubusercontent.com/6943031/129475604-128005c8-ab10-41ec-b0c2-9e56ea39c2a3.png)

I don't think I need to write anything else. I just AFK'ed for some time.

**Comment by GirafiStudios** [comment]
Bug cause by other mod. We follow vanilla spawn limit rules, somebody must be messing with it.
