### ISSUE TITLE
Server crash using a composter by residents

### ISSUE THREAD

**Issue by XionioXMaster** [TeamMetallurgy/Atum2#328]
Some blocks, judging by the video, prevented the villager from using the composter, which caused the server to crash
https://youtu.be/irUSFa4C1iI
https://paste.ubuntu.com/p/VN24RYkgb3/

**Comment by ahdg6** [comment]
I have the same issue.

**Comment by sscards55** [comment]
I think there will have to be a rewrite of all AI task for Atum Villagers.

**Comment by GirafiStudios** [comment]
So the crash is 100% not caused by Atum, something is messing with a the vanilla method.
That compositing is not working is definitely a problem though, I´ll look into it.

**Comment by GirafiStudios** [comment]
Actually, it is working just fine. Just takes a little while, before they start doing it :)
