### ISSUE TITLE
Return to Atum after death in foreign dimension resets bed spawn point

### ISSUE THREAD

**Issue by ZigTheHedge** [TeamMetallurgy/Atum2#333]
Well, subj. 
If config option is set to "Start in Atum" player will respawn in Atum indeed, but not at his bed.

Forge: 36.2.2

**Comment by GirafiStudios** [comment]
Due to how spawn points is handled nowadays, this is borderline impossible to achieve. 
As it´s working for its current intentions, with starting in Atum and playing there, this is very low priority.
Might get around to it at some point eventually.

**Comment by StevenDoesStuffs** [comment]
I'm really not sure how this works, but if I remember correctly, something in the FTB interactions modpack (1.12) starts you off in a skyblock dimension, and then you progress to the overworld. They somehow managed to get bed respawn to work in both dimensions I think.

**Comment by GirafiStudios** [comment]
Should be fixed by https://github.com/TeamMetallurgy/Atum2/pull/391 :)
Might be a little while before a new build is out though, as I´m not home.
