### ISSUE TITLE
Sarfhagus can be dupe

### ISSUE THREAD

**Issue by XionioXMaster** [TeamMetallurgy/Atum2#339]
If you use some kind of mod that breaks 2 blocks at once, you can dup this sarfophagus

https://user-images.githubusercontent.com/86433158/131208362-ba45704c-1f72-4800-988e-b264c58e504d.mp4

In my case, EnigmaticLegacy Astral Breaker

**Comment by sscards55** [comment]
Please remove the video and the description, and private message @GirafiStudios.

**Comment by GirafiStudios** [comment]
It´s fine sscards.
I´ll look into it :)

**Comment by XionioXMaster** [comment]
> It´s fine sscards.
> I´ll look into it :)
You can also break pyramids using Astral Breaker

**Comment by sscards55** [comment]
Could you open a separate issue for that, please?

**Comment by XionioXMaster** [comment]
> Could you open a separate issue for that, please?

Unfortunately, I have little time, I will soon get to work

**Comment by GirafiStudios** [comment]
> > It´s fine sscards.
> > I´ll look into it :)
> 
> You can also break pyramids using Astral Breaker

That´s an issue with the Astral Breaker, it´s not respecting the BlockEvent.BreakEvent.
