### ISSUE TITLE
Full translation into Russian from our server Made In Abyss

### ISSUE THREAD

**Issue by XionioXMaster** [TeamMetallurgy/Atum2#341]
TagasZX, DeZoWaRe

[ru_ru.txt](https://github.com/TeamMetallurgy/Atum2/files/7072124/ru_ru.txt)
Indicate the author of the translation my  server, if it's not difficult for you) Also change .txt to .json. Oh yes, who am I teaching))

**Comment by GirafiStudios** [comment]
You formatting seems to be very off. Not sure if it´s because you saved it as .txt or what you did.
If you wish to update the Russian localization, please do so with a Pull Request instead, based of the current Russian localization :)
