### ISSUE TITLE
Right-clicking Quern with a single Blaze Rod duplicates it

### ISSUE THREAD

**Issue by NillerMedDild** [TeamMetallurgy/Atum2#342]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3122

Reproduction steps can be seen here: https://github.com/NillerMedDild/Enigmatica6/issues/3122#issuecomment-907870210

### Versions
- Forge-1.16.5.36.2.2
- [Atum-1.16.5-2.2.6.jar](https://www.curseforge.com/minecraft/mc-mods/atum/files/3406907)

**Comment by GirafiStudios** [comment]
Does not reproduce with just Atum 2.2.6 alone, must be some sort of mod interaction, caused by another mod in Enigmatica 6.

**Comment by NillerMedDild** [comment]
Right, Blaze Rods can be placed in-world in Enigmatica 6, I believe Supplementaries adds that feature. I should have mentioned that 😅 Does the Quern have any special handling for placeable blocks when right-clicked with them?

**Comment by GirafiStudios** [comment]
Not in particular, no.
Only think I can think of, is if Supplementaries is somehow triggering onBlockClicked

**Comment by NillerMedDild** [comment]
Alright, thanks for the help! I reported the issue on Supplementaries tracker: https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/133
