### ISSUE TITLE
Cannot find warlord

### ISSUE THREAD

**Issue by Avalonzo** [TeamMetallurgy/Atum2#345]
I'm currently playing the better minecraft plus modpack and there is a quest to kill a warlord but I can't find one been looking for the past 4 hour could it be a bug or is there a special way or thing I need to do to get a warlord to spawn.

**Comment by LeoColman** [comment]
I couldn't find anything related to Warlord spawning around the code. 
This might be a bug

**Comment by Shadowclaimer** [comment]
Warlords are not supposed to spawn. They are not currently in the mod and are only available through manual spawning/spawn eggs.

**Comment by LeoColman** [comment]
@Shadowclaimer 
Is there a plan on how the Warlord will work? Perhaps I can help you with the implementation?

**Comment by Shadowclaimer** [comment]
There are plans for the Warlord, it was going to get put in at one point with a new dungeon but we pushed it back. But I appreciate the enthusiasm!
