### ISSUE TITLE
Game crash after entering portal

### ISSUE THREAD

**Issue by charlielyne1** [TeamMetallurgy/Atum2#347]
Game crashes after a couple of minutes after entering the portal. Playing singleplayer.
Playing the "Better Minecraft Plus" modpack. version 22
Crash report is large so here's it's pastebin: https://pastebin.com/cvrCM2Mj

**Comment by GirafiStudios** [comment]
Could be caused by a lot of things, and does not necessarily have anything to do with Atum.
Try removing the mod Performant. Tends to cause more issues, than it fixes.
