### ISSUE TITLE
all god bows use the wrong sprite

### ISSUE THREAD

**Issue by kuba26038** [TeamMetallurgy/Atum2#350]
![Przechwytywanie](https://user-images.githubusercontent.com/81324988/134770825-03fd50dd-9640-42f7-8f72-57859d44acac.PNG)
here they are

**Comment by sscards55** [comment]
This does not happen with just the mods and it's dependencies. What other mods are you using?  What version of forge, and what version of the mod are you using?

**Comment by GirafiStudios** [comment]
Does not happen with Atum 2 only.
