### ISSUE TITLE
Crash server 

### ISSUE THREAD

**Issue by XionioXMaster** [TeamMetallurgy/Atum2#354]
https://paste.loliidc.cn/?6aae84d635d375d7#GEm8xsa3RtwVcdkmhJjXJK4qznrW1G9BWDfGGoqVx3Wb

**Comment by GirafiStudios** [comment]
Can you try setting it up locally? The crashlog you provided provides little to no information.

**Comment by GirafiStudios** [comment]
Closing as no Forge test case have been provided.
