### ISSUE TITLE
Re #355: Issue with crates not closing happens with only Atum and curios api installed

### ISSUE THREAD

**Issue by Kaleidio** [TeamMetallurgy/Atum2#357]
mc 1.16.5 forge 36.2.8 atum 2.2.8

This "not closing" issue can still result in server lockup.  **_No other mods need to be installed._**

Vanilla chests do not exhibit the same behaviour no matter for how long I attempt to get them to whilst in the Atum dimension

Screenshots of proof this bug actually exists:
![2021-10-12_07 38 54](https://user-images.githubusercontent.com/82226641/136905265-ee6cb84e-9353-45e7-ad88-9d8bb07600bf.png)
![2021-10-12_07 41 06](https://user-images.githubusercontent.com/82226641/136905291-24929865-3cf2-4630-bf66-58404df40849.png)

logs:
(has nothing useful, debug log did not show up)
[latest.log](https://github.com/TeamMetallurgy/Atum2/files/7327509/latest.log)

**Comment by Kaleidio** [comment]
F.Y.I you can get this to trigger yourself by spamming the crate.

**Comment by GirafiStudios** [comment]
I´ve tried spam-opening a Crate on a server for about 10 minutes now, without any luck at all.
I can´t really do much, if I can´t reproduce it myself, when there is no crash log either.

Just to be clear, you´re playing on an actual server, not just "Open to LAN"?

**Comment by Kaleidio** [comment]
Yes I am VERY sure it's just singleplayer.  No LAN, no server.

I have a ryzen 5800x and rtx 3080.  this is a genuine bug.  I'm curious if it's something specific to AMD CPU processors, for example if you're using a library for that model in some sort of fashion that has render code in it.  lately some mods have been breaking due to ryzen's difference in usage of cache.

**Comment by Kaleidio** [comment]
The only thing I can suggest is that the crate code be extremely similar to, if not inherited from, the vanilla chest class.  from what I can tell here your current code has the capability to fail to see if the chest was properly closed.  might you be using a deprecated or missing method for the crate's closure process?

**Comment by Kaleidio** [comment]
in fact it might purely just be that the animation of the block is getting stuck in the open position and the client just locks up because of that or something.

**Comment by Kaleidio** [comment]
Happens with Java 8 u 304

okay so I was watching my mouse clicks whilst testing, and it seems to happen if you click twice without moving the mouse.  apparently this counts as a double-open somehow, but the game lets the block stay in the open state because it thinks it only has to close one of two opens

make sure the code has a failsafe to not fire the open method if it's already open.

**Comment by GirafiStudios** [comment]
Looked at it a bit now. For sure can´t be the capabilities, as it´s defaulting to the exact same code as chests uses.
Could be related to how the GUI Container is opened, that´s certainly a possibility.

For now, I added some null checks for world in the Tile Entity for the Crate, as there is a chance it could be that.
If you could attempt with the build here, that would be great! :)
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.16.5%20Jenkins/297/

**Comment by GirafiStudios** [comment]
Could you try the build previous to the one I linked you?

**Comment by GirafiStudios** [comment]
Thanks!
I´m able to reproduce that crash too actually. The config is not generating properly, will look into that now.

**Comment by GirafiStudios** [comment]
Sorry for the very late response, never got around to try to fix the config issue. Ended up reverting the whole thing, as I found out it was not possible due to Forge load order.

Could you try this build, so see if it fixes your issue? :)
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.16.5%20Jenkins/303/

**Comment by Kaleidio** [comment]
hiya, gonna start running tests now, sorry for late response

**Comment by Kaleidio** [comment]
no crash.  testing crate itself

**Comment by GirafiStudios** [comment]
Thanks for checking, glad it fixed it!
Part of the release on CurseForge today too.

**Comment by Kaleidio** [comment]
yeah it looks like the crate does sync as well, so all good.
