### ISSUE TITLE
Ore configs have no effect.

### ISSUE THREAD

**Issue by Neamow** [TeamMetallurgy/Atum2#359]
Atum: 1.16.5-2.2.8.jar
Forge: 36.2.6

Hello,

I've been trying to change the ore gen in Atum in this version using the config, but it looks like changing it has no effect?

For example I've tried removing the atum iron ore. First I changed the "Iron count, set to 0 to disable" value to 0, but the ore still generated. Then I tried changing "Iron max height" to 0 and "Iron vein size" to 0 as well. Iron ore still generates.

I made sure to reload the game and try a new world each time.

Can you please have a look?

Thanks!

**Comment by GirafiStudios** [comment]
Reverted this change, as it´s impossible to get working when generating new configs, due to Forge load order.
