### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by ShootToKillSTK** [TeamMetallurgy/Atum2#362]
[crash-2021-11-11_00.31.44-fml.txt](https://github.com/TeamMetallurgy/Atum2/files/7531203/crash-2021-11-11_00.31.44-fml.txt)

**Comment by GirafiStudios** [comment]
Can´t even start to attempt fixing this, due to lack of information. You´ve not mentioned when it´s crashing, what is causing it to crash, or anything like that.
