### ISSUE TITLE
EFM Compatibility Mod

### ISSUE THREAD

**Issue by TakoDile** [TeamMetallurgy/Atum2#363]
This isn't really and issue, but I had a question for the mod authors and this was the best way I could think of to reach them. I'm working on a compatibility mod between Epic Fight Mod and Atum 2 (mainly Atum 2's armors), and while working on it I tried to run Atum 2's source code in IntelliJ but I ran into this error java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.teammetallurgy.atum.misc.AtumConfig$Helper.get(net.minecraftforge.common.ForgeConfigSpec$ConfigValue)" is null. I'm relatively new to IntelliJ and java coding in general and I wanted to ask the Atum 2 authors if they could help me identify whats causing this issue.  Please note that I do no intend to redistribute this mod, I'm doing this solely for my own personal use.

**Comment by GirafiStudios** [comment]
Please use our Maven, as described in the README here on Github :)
Sounds like you´re directly using the latest source code, which have that issue you´re describing.
