### ISSUE TITLE
Remove/Give option to remove "fully charged" condition for Anubis Wrath/Nepthys Banishing

### ISSUE THREAD

**Issue by Himynameissomeone** [TeamMetallurgy/Atum2#364]
I've recently come across a mod called Epic Fight Mod, which fits well with Atum 2's RPG content: Atum 2 items work extremelly well with the Epic Fight Mod, especially with different kinds of weapons. Even better, most of the Atum 2 item attributes work with the mod.

However, certain items with the condition "fully charged" cannot be triggered with the mod. Some examples include: 

- Anubis Wrath
- Nepthys Banishing

Where their innate abilites (double dmg upon condition & fully charged weapon) don't work probably because the vanilla crosshair mechanic is not supported. 
Would it be possible if:
A) The "fully charged" condition gets removed like the 1.12 versions of the game (I recall both Anubis/Atum didn't have charging conditions and just boosted dmg)
B) A line in config perhaps that could disable the condition.

It's just a shame that I can't use certain abilities when both mods work so well together.

Thanks for the help!

**Comment by GirafiStudios** [comment]
Sounds like an issue on their end, we´re using LivingHurtEvent to increase the damage.
A config option is not going to happen - it worked exactly like this in 1.12 as well.

**Comment by Himynameissomeone** [comment]
Not trying to bother u ;-; (I rlly appreicate ur work with the mod) but... The horus' weapon exclusively works despite it being one of the "charge" weapons. Would there be a reason for this? Is the horus dagger coded differently perhaps?

**Comment by GirafiStudios** [comment]
The "fully charged" part of the code is exactly the same, so it´s for sure not that causing it to not work.
