### ISSUE TITLE
How I love sarfophages and their dupe

### ISSUE THREAD

**Issue by XionioXMaster** [TeamMetallurgy/Atum2#365]
https://youtu.be/X4Ki9oDmKYc

Last version Create + Last version Atum 2 1.16.5

**Comment by sscards55** [comment]
Please provide version numbers.

**Comment by GirafiStudios** [comment]
Caused by Create, since they seem to allow the movement of TileEntity blocks, that can´t be moved by pistons. Nothing that can be done on our end.
