### ISSUE TITLE
Feature Request:  Configs for weapon/armor stats

### ISSUE THREAD

**Issue by Boolyman** [TeamMetallurgy/Atum2#368]
Would you be able to give us pack devs a bit more control over the gear stats that are on Atum items?  In packs like mine, that have mods like Champions or Scaling Health, your items just aren't strong enough to be worth getting.  If you gave pack devs a few configs to adjust it would make your mod more versatile.

**Comment by GirafiStudios** [comment]
It´s impossible due to load order in Forge, unfortunately.
There used to be a few mods out there, that allowed you to alter armor/weapons/tools stats - might be worth looking into if that´s still the case :)
