### ISSUE TITLE
Mask of Nuit

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum2#37]
![mask_of_nuit](https://user-images.githubusercontent.com/2214143/40383985-442fa952-5dd0-11e8-9531-99047a7c7388.png)

Effect:

"Umbral Cloak" "Decreases range that enemies will approach you."

Halves the range that enemies will engage you.

Needs a render as part of this full armor set.

**Comment by GirafiStudios** [comment]
Closing as render will most likely not be done for a while.
Information moved to spreadsheet.
