### ISSUE TITLE
Update broke Tetra workbenches

### ISSUE THREAD

**Issue by minmei900** [TeamMetallurgy/Atum2#370]
Updated yesterday to 1.16.5-2.2.9. Could not open a Tetra-based workbench. Reverting fixed the issue.

**Comment by GirafiStudios** [comment]
Unable to reproduce. Also would make little to no sense, considering the changes in 2.2.9.
Tested with the following mods:
![0rQyisf](https://user-images.githubusercontent.com/6305377/144444793-006fb940-55f2-4b34-8723-fc47f21d1c95.png)

**Comment by sscards55** [comment]
There really should not be any issues. Most of the update was just updating tags and translation files. The only thing that changed was the Crate null checks, but I don't see how that would cause issues.
Are there any errors in the console when you try to open the table?

**Comment by minmei900** [comment]
NVM. Upgraded again and could not reproduce.  Must have been a different issue, maybe in Tetra. Thanks for the quick response!
