### ISSUE TITLE
Tropicraft biome empty loot

### ISSUE THREAD

**Issue by Gattoartico** [TeamMetallurgy/Atum2#371]
According to the server Aquaculture is missing loot in Tropicraft. It told me to report it btw pls don't crucify me Girafi

console text:
[00:15:02] [Server thread/ERROR] [aquaculture/]: Loot was empty in Biome: tropicraft:tropics. Please report on Github

**Comment by sscards55** [comment]
What version of the game and mods are you using?

**Comment by Gattoartico** [comment]
game version is 1.16.5, Aquaculture version is 2.1.21, Tropicraft version is 9.0.1 beta 64

**Comment by Gattoartico** [comment]
shit just realized I opened this in the wrong mod pls kill me now Cards
