### ISSUE TITLE
Patrols seem to have no spawn cap

### ISSUE THREAD

**Issue by NillerMedDild** [TeamMetallurgy/Atum2#375]
When staying in one place in Atum, the amount of Patrols gradually increases if you don't kill them. 
I would have expected/hoped that there was a cap to keep the entity count sane, below 30 patrol units near one player for example.

PR with context and a screenshot: https://github.com/NillerMedDild/Enigmatica6/pull/3943#issuecomment-1000117282

**Comment by GirafiStudios** [comment]
Any chance I could get you to test this with just Atum? :)
I´ve had reports of it before, but I´ve not been able to reproduce it - so I´m suspecting perhaps another mod is somehow breaking the spawn cap.

**Comment by GirafiStudios** [comment]
This is what I get after 1 hour. Have been going up and down in that time too.
![image](https://user-images.githubusercontent.com/6305377/147659594-d1cedba2-55ab-42fc-9c08-6349fbcd5aa4.png)

So my assumption that another mod is somehow breaking the spawn caps for Atum patrols, seems to be correct.

**Comment by NillerMedDild** [comment]
Damn, we'll find a way to limit the spawns then, thank you for your assistance 😄

**Comment by GirafiStudios** [comment]
Please do let me know if you figure anything out, as I would love to know what´s going on :)
