### ISSUE TITLE
Confirmed 1.16.5 bug Quark invintory sort feature messes up cammels

### ISSUE THREAD

**Issue by SteamDoge9000** [TeamMetallurgy/Atum2#376]
this will cause a crash, but only when the action is done, afterwrads you can still acess the cammel
while it would be a pain to try and dig it up, I can tell you one thing, when the action is done and you go back into the affected world and open the cammels inventory, the issue seems to have been the result of a "forced" sort or something on the slots that should not have been sorted

in this case, if you have a cammel wtih crates and armor, and press the sort key (and/or keybind) from quark, it will make the game crash presuably becuase it moves those amor/chest slots and forces them into places they should not go

If my thinking is correct, having those slots be treated by quark as if they were armor slots or whatever to prevent them from being sorted by it should fix this issue

Steps to Repo

1. have this mod and quark
2. Load up a tamed cammel wtih a armor/saddle and one crate, (preferably on the right side)
3. hit the quark sort button or the quark inventory sort keybind (either one will work)
4. crash
5. Restart game and rejoin affected world
6. open cammels Inventory 
7. find that all the items in the equipment slots are messed up

Sidenote: surpisingly, even if the crate is no longer in that slot and is replaced by a different item, it will still keep its inventory, might be intetinoal or a uninitentoal result

addional notes: if you are going to try to fix this, maybe also try to relocate the quark icons if possable to  a more apropiate spot
<img width="290" alt="image" src="https://user-images.githubusercontent.com/38770780/147887979-8f9cd5b4-c4b3-4aca-a08f-56227ab29edc.png">

**Comment by GirafiStudios** [comment]
Fixed the crash in https://github.com/TeamMetallurgy/Atum2/commit/a1d570089b940f6e31907f0ada90b657bb2b8b1f
I´ll see if it´s possible to disable Quark sorting for the Camel inventory all together, as it allows to sort items into slots, where they shouldn´t be able to go.
