### ISSUE TITLE
[Request] Block Atum Patrols with Torchmaster Mega Torch

### ISSUE THREAD

**Issue by NillerMedDild** [TeamMetallurgy/Atum2#377]
In the mod [Atum](https://www.curseforge.com/minecraft/mc-mods/atum) patrols spawn frequently around the player. 
Allowing the Mega Torch from [Torchmaster](https://www.curseforge.com/minecraft/mc-mods/torchmaster) to block them would be lovely for when building in the dimension.

I'm unsure which mod would need to implement this, so I'm posting it in both trackers 😄 

Torchmaster issue: https://github.com/Xalcon/TorchMaster/issues/173

**Comment by GirafiStudios** [comment]
If I understand Torchmaster correctly, it only prevents natural spawns. 
The Bandit patrols is a CustomSpawner like the villager raids or phantoms, so I assume why Torchmaster is not working.
Bandits also only spawn when it´s daytime - although torches will prevent them from spawning.

Seems like it´s something Torchmaster would have to implement on their end, so closing this. Although if there is anything I can do on my end, let me know :) (If Xalcon says there is for example)

**Comment by NillerMedDild** [comment]
Alright, thanks 😊
