### ISSUE TITLE
Body of Nuit

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum2#38]
![body_of_nuit](https://user-images.githubusercontent.com/2214143/40384048-716790ec-5dd0-11e8-9fc8-0f8bfed802d5.png)

Effect:

"Umbral Protection" "You are immune to Wither and attackers are Withered."

You can no longer be impacted by Wither from enemies. Enemies that hit you have a 25% chance to suffer Wither I for 4 seconds. There is a spray of black particles when they strike you if this triggers.

Needs a render as part of this full armor set.

**Comment by GirafiStudios** [comment]
Closing as render will most likely not be done for a while.
Information moved to spreadsheet.
