### ISSUE TITLE
Player-Made Stonewardens + Stoneguards show up as Hostile Mobs

### ISSUE THREAD

**Issue by TheGameAce** [TeamMetallurgy/Atum2#382]
Title. Minimap shows player-made guards and wardens as hostile entities. Similarly, golems of all sorts (Vanilla and modded) attempt to target the guards and wardens.

**Comment by GirafiStudios** [comment]
That playermade stoneguards/stonewardens shows up as hostile is a problem with the minimap mod (Or you´re not on the 1.16 version of Atum).
"Wild" Stoneguards are not meant to attack playermade stoneguards - unless attacked. I´ll look into that getting fixed.
The rest is intended.

**Comment by TheGameAce** [comment]
I'm running 1.16.5 latest, so it's not that. Might be because of using the same mob (presumably) for both player-made and "wild" versions, which would explain why they show up as hostile via the minimap still.

Otherwise I feel I should clarify that I didn't test "wild" guards vs player-made. I was referring to overworld golems such as Iron, and modded variants, which end up targeting player-made guards, presumably for the same reason the minimap counts them as hostile.

**Comment by GirafiStudios** [comment]
Friendly and hostile stoneguards are separate entities. Friendly marked as Misc (Only real option that makes sorta sense) and Hostile marked as Hostile.

Making the vanilla mobs not attack would require changing vanilla behavior, which is probably not something we want to do.
