### ISSUE TITLE
azucat

### ISSUE THREAD

**Issue by Azuriuz** [TeamMetallurgy/Atum2#386]
so my sweet lil serval texture only works with the nametag 'azure' instead of 'Azure'
Shadow said to make a note here about it lol
![image](https://user-images.githubusercontent.com/50718369/163882542-b4465f21-85f1-4645-be11-8dcb1220cf6b.png)

**Comment by Azuriuz** [comment]
Mind you I'm on the 1.16.5 version if that makes a difference*

**Comment by Shadowclaimer** [comment]
Confirming Shadow said that.

**Comment by TopPercentageRattata** [comment]
https://github.com/TeamMetallurgy/Atum2/blob/master/src/main/java/com/teammetallurgy/atum/client/render/entity/mobs/ServalRenderer.java

line 31 here is the culprit

if (entity.hasCustomName() && entity.getCustomName().getString().equals("azure")) {

**Comment by GirafiStudios** [comment]
Fixed :)
Also added Azu and Azuriuz as alternate names.
