### ISSUE TITLE
Legs of Nuit

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum2#39]
![legs_of_nuit](https://user-images.githubusercontent.com/2214143/40384159-ced29af6-5dd0-11e8-9ca1-0ab263b795c0.png)

Effect:

"Umbral Rush" "You can jump higher and take less falling damage."

Mirrors the effects of Jump Boost I permanently while worn. Which automatically decreases fall damage and increases your jump height. A small burst of white particles from your legs downward when you jump.

Needs a render as part of this full armor set.

**Comment by GirafiStudios** [comment]
Closing as render will most likely not be done for a while.
Information moved to spreadsheet.
