### ISSUE TITLE
Yeah, Issue #274 Crashing isn't fixed, or I have something very similar.

### ISSUE THREAD

**Issue by Ometia** [TeamMetallurgy/Atum2#397]
So I'm getting a repeat of issue #274 Crashing. Yes, I reinstalled minecraft, yes I was already using the curseforge launcher, so what ever is getting corrupted needs to be isolated. I left a comment on the issue there, but want to create a new issue here because... one time I got a DIFFERENT report saying that it was terrain generation that was the issue, not the entity collision check.  I've checked other dimensions, (Blue skies, Twilight Forest, Nether, End, etc.) and they all seem fine. It appears to be specific to Atum. If I had to guess, I'd say that part of the terrain generation is causing the collision (due to the fact that it seems to alternate every now and then). Additionally, I have the same crash when I play the custom pack on my friend's server (I develop, he runs), so whatever corruption is going on is apparently common and needs to be found. Maybe this is an issue just mimicking #274 Crashing, but that's one heck of a coincidence. I can provide logs if asked for, but here's just the crash report(s):

[crash-2022-07-14_23.41.17-server.txt](https://github.com/TeamMetallurgy/Atum2/files/9126222/crash-2022-07-14_23.41.17-server.txt)

[crash-2022-07-15_15.44.08-server.txt](https://github.com/TeamMetallurgy/Atum2/files/9126223/crash-2022-07-15_15.44.08-server.txt)

[crash-2022-07-15_18.48.42-server.txt](https://github.com/TeamMetallurgy/Atum2/files/9126224/crash-2022-07-15_18.48.42-server.txt)

[crash-2022-07-16_10.36.09-server.txt](https://github.com/TeamMetallurgy/Atum2/files/9126225/crash-2022-07-16_10.36.09-server.txt)

**Comment by GirafiStudios** [comment]
The 2nd crash report mentions ruins. Try to disable them, to see if that makes the crashing stop.
Also you´re not even using the latest version of Atum 2 for 1.16.5?

**Comment by Ometia** [comment]
Turns out I was not using .....11 (most recent for 1.16.5), I was using .....10, but doesn't matter 11 crashes too. Attempting the ruin fix, will respond in a few minutes (my modpack takes a bit to boot up).

**Comment by Ometia** [comment]
That did it, thanks!
