### ISSUE TITLE
Curator can't trade

### ISSUE THREAD

**Issue by Porcy** [TeamMetallurgy/Atum2#399]
Version 1.16.5-2.2.11
Modpack: Enigmatica 6 expert
Right-clicking the curator villager with a relic doesn't work (he makes the 'no' sound)
Throwing the relic near the curator makes the curator look at it but nothing more.

**Comment by TopPercentageRattata** [comment]
Do you have mobgriefing off? Like piglins in vanilla I believe they might not be able to pick up items if that game rule is changed.

**Comment by Porcy** [comment]
Yup. MobGriefing False prevents bartering with Curator as well... 
Would be nice to be able to barter with a right-click on him like suggested (wrongly) in the Wiki.

**Comment by Shadowclaimer** [comment]
Which wiki?

**Comment by Porcy** [comment]
https://atum.fandom.com/wiki/Curator
I just edited it this morning to correct this error and someone reverted my change.

**Comment by Shadowclaimer** [comment]
Just checking there's another wiki out there that's not maintained by us.

I made the same change you made again, we'll see if it takes. I might have to yell at someone haha.

**Comment by GirafiStudios** [comment]
Working as intended, following vanilla standards.
