### ISSUE TITLE
Feet of Nuit

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum2#40]
![feet_of_nuit](https://user-images.githubusercontent.com/2214143/40384339-3941003a-5dd1-11e8-9094-a57a9a9eef83.png)

Effect:

"Umbral Swiftness" "You move faster at night."

While it is night time you have 25% extra movement speed base.

Needs a render as part of this full armor set.

**Comment by GirafiStudios** [comment]
Closing as render will most likely not be done for a while.
Information moved to spreadsheet.
