### ISSUE TITLE
Ra armor still takes fire damage

### ISSUE THREAD

**Issue by DWiz24** [TeamMetallurgy/Atum2#400]
When wearing full Ra armor, the damage sound still plays, and the armor takes durability damage from lava. Damage sound also plays when on fire.

On Enigmatica 6 expert

**Comment by GirafiStudios** [comment]
What version of Atum 2 are you using?

**Comment by DWiz24** [comment]
Atum-1.16.5-2.2.11

**Comment by GirafiStudios** [comment]
Should be fixed by https://github.com/TeamMetallurgy/Atum2/pull/389
I forgot to release a new version apparently with the fix - will get it released.
