### ISSUE TITLE
Config Atum starting structure not working with vanilla structure

### ISSUE THREAD

**Issue by OverEarth12** [TeamMetallurgy/Atum2#402]
Other Atum's structures work fine.
![image](https://user-images.githubusercontent.com/56574543/195105177-fac69a36-ce3f-47e8-9943-d0b2af620d1e.png)
![2022-10-11_20 18 40](https://user-images.githubusercontent.com/56574543/195105216-6bd25f1c-8b6c-44d5-ad1f-f3d8e91889df.png)

**Comment by GirafiStudios** [comment]
It won´t work with stuff that´s generated the way villages and bastions are for sure. It grabs a specific structure feature, based on the file name.
