### ISSUE TITLE
Unable to burn crystal glass

### ISSUE THREAD

**Issue by ltlt666** [TeamMetallurgy/Atum2#404]
In Minecraft 1.16.5 (Forge 36.2.34,Mod 2.2.12), i can not  burn crystal glass in furnace or kiln,it only give me a minecraft:glass

**Comment by GirafiStudios** [comment]
Another mod is breaking it, it works fine with just Atum 2 with the versions specified.
I think I remember there being a weird issue, that having CraftTweaker installed caused it. But I don´t really remember.
