### ISSUE TITLE
Anubis's Wrath - title of the effect is different from other artifacts

### ISSUE THREAD

**Issue by alfieboris** [TeamMetallurgy/Atum2#405]
I know It's not a big deal but my ocd is killing me. It looks like this for every stage of the sword. 
And I also wanted to ask about Osiris's Mercy if it is intentional that even if you can't enchant it in an enchanting table you can still apply enchantments to it in an anvil?
See pictures of Anubis's Wrath below.

Here's Anubis's Wrath
![Anubis's Wrath without shift](https://user-images.githubusercontent.com/47575790/210014319-aa14f268-e844-4a5e-ba88-61f50d9d19d1.png)
![Anubis's Wrath with shift](https://user-images.githubusercontent.com/47575790/210014643-19872814-c782-49f9-a842-b7b9660f4e6b.png)

Here's Ptah's Decadence (for example)
![Example without shift](https://user-images.githubusercontent.com/47575790/210014482-65adfae2-c261-4777-b2e3-b338a05fda55.png)
![Example with shift](https://user-images.githubusercontent.com/47575790/210014646-993dd86c-dee0-479a-a5a3-12bb7fbaee02.png)

**Comment by Shadowclaimer** [comment]
This is up to Girafi but I see what you mean the Soul Unraveler stuff should be underneath the attack damage/attack speed? Unsure if that's possible but if it is yea it should be like that.

And no, Anvil enchants shouldn't work <.< that's an oversight.

**Comment by alfieboris** [comment]
Yeah every artifact has the effect written below except this I just showed this artifact because I didn't want to show all of them.
