### ISSUE TITLE
[1.16.5] crash with presence footsteps when spawning desert wolf

### ISSUE THREAD

**Issue by Kaleidio** [TeamMetallurgy/Atum2#408]
somehow the footsteps mod is confusing it for a bipedal entity, I was wondering if this was an issue that could be fixed on your side since vanilla wolves don't crash this way, such as if the entity is inheriting the wrong class:

https://github.com/PaintNinja/Presence-Footsteps-Forge/issues/11

**Comment by GirafiStudios** [comment]
It´s crashing in their code, so most likely nothing I can do about it.

They spawn in Limestone Crags, Limestone Mountains,& Sand Hills.
