### ISSUE TITLE
Geb's Toil (Language file)

### ISSUE THREAD

**Issue by GoldenTotem** [TeamMetallurgy/Atum2#409]
Geb's toil didn't consume durability in atum-1.12.2
But it does in atum-1.16.5-2.2.11
If it works like a normal shovel, the language file should be changed.
![Snipaste_2023-02-16_20-58-20](https://user-images.githubusercontent.com/70516358/219372171-96f66222-893f-47d0-a82b-e1da4ed19450.png)

**Comment by GirafiStudios** [comment]
Durability have nothing to do with Geb's Toils special effects. That it now consumes durability was just a slight design change in 1.16
Fatigue is what causes you to lose hunger faster, which using a shovel also does slightly. With Geb's Toil it simply doesn't take any fatigue at all.

**Comment by GoldenTotem** [comment]
> Durability have nothing to do with Geb's Toils special effects. That it now consumes durability was just a slight design change in 1.16 Fatigue is what causes you to lose hunger faster, which using a shovel also does slightly. With Geb's Toil it simply doesn't take any fatigue at all.

Ok, I understand. Because of the previous translation file, I misunderstand it.
