### ISSUE TITLE
Montu pharaohs doing too much damage

### ISSUE THREAD

**Issue by Beefandbooze** [TeamMetallurgy/Atum2#410]
Title. Montu pharaohs are doing a lot of damage despite being almost full health

https://user-images.githubusercontent.com/125605710/219478429-8a8e0194-d03d-46a7-ba2e-b741d18ef6b3.mp4

I am wearing full diamond armor with prot 4 in the clip

**Comment by Beefandbooze** [comment]
This is on the latest version btw

**Comment by GirafiStudios** [comment]
Once you hit a Montu's Pharaoh it gets increased damage for 3 seconds & then goes back to normal after that.
Just tested it & it works correctly - looks to be working correctly in your video as well :)
