### ISSUE TITLE
[Question] Ra's Fury

### ISSUE THREAD

**Issue by alfieboris** [TeamMetallurgy/Atum2#411]
The 2.2 atum changelog mentioned that the Ra's Fury bow is supposed to deal bonus damage to already burning enemies but I don't think it does. It does the same damage to burning and non-burning enemies.

**Comment by GirafiStudios** [comment]
It actually does increase the damage by 50% :)

https://github.com/TeamMetallurgy/Atum2/blob/master/src/main/java/com/teammetallurgy/atum/entity/projectile/arrow/ArrowFireEntity.java#L43-L46
