### ISSUE TITLE
[Balance] Seth's Venom

### ISSUE THREAD

**Issue by alfieboris** [TeamMetallurgy/Atum2#412]
- I think that the Seth's Venom poison could use a buff because it is pretty underwhelming. 
- Because of immunity frames if you have Flame enchant on the bow it does 2 ticks of poison and 2 ticks of fire = 4 tick damage (Flame on normal bows does 4 burn ticks so it's the same as a regular bos with Flame).
- Also many enemies are immune to posion so fire is much better (and atum's undead mobs take more damage from fire)
- Bows kill most weaker mobs in one hit anyway (with Power V) so a buff wouldn't break anything 

My suggestions:
1) Extend the duration of the poison (so it has 4 or more damage ticks)
2) or Give it poison II instead of poison I (with the same duration it would do more damage and it would tick faster)
3) or Give it bonus damage to already poisoned enemies
4) or Give it a new effect (you could add a new debuff to the mod called for example "Venom", "Seth's Venom" - it could be almost the same as poison but not that many enemies would be immune to it)

**Comment by Shadowclaimer** [comment]
Not bad suggestions. We recently made the Ra bow deal bonus damage to burning enemies, I think doing something similar for Seth's Venom or simply buffing the poison damage would be great.

We could also look into making bandits and such take bonus poison damage as living enemies.
