### ISSUE TITLE
[1.16.5] Arrows fired by bows have both custom and vanilla particles

### ISSUE THREAD

**Issue by Kaleidio** [TeamMetallurgy/Atum2#414]
Unsure if this was intended as some arrows only show the secondary particles during crit, as if they were intended to replace the regular particles rather than emit both.

**Comment by GirafiStudios** [comment]
It's impossible to replace the original vanilla particles unfortunately. At least in 1.16.5.
Would love to, if it was possible!

**Comment by Kaleidio** [comment]
I see, it seems Mojang only allows an override to a method for particle emission in AbstractFireballEntities.  Thanks Mojang.
