### ISSUE TITLE
Dimension not working

### ISSUE THREAD

**Issue by AwMan3703** [TeamMetallurgy/Atum2#416]
I have downloaded the mod as zip, unzipped it and compiled it ( `./gradlew build` ), but when i create a world and make a portal it does not create the atum dimension (i just sit inside the portal and it does nothing), and i can't go there through commands either ( i tried with `/execute in atum:atum run tp [myName] ~ ~ ~` ).
Anyone knows how to solve this?

**Comment by GirafiStudios** [comment]
There is a reason it's not released for newer versions of Minecraft.
