### ISSUE TITLE
Kiln Disappearing

### ISSUE THREAD

**Issue by bubbaboogs** [TeamMetallurgy/Atum2#422]
Atum 2 1.16.5-2.2.12 Forge 36.2.34

After I build the kiln multiblock and go to another dimension it disappears. The blocks are gone and nothing is left where it was. This happens with any dimension and it happens consistently.

Right after building kiln:

![2024-01-19_21 29 34](https://github.com/TeamMetallurgy/Atum2/assets/73847191/01279ab2-43b4-49aa-8196-ffc00b39d8f3)

After coming back from another dimension:

![2024-01-19_21 30 16](https://github.com/TeamMetallurgy/Atum2/assets/73847191/5d36c206-8fd3-4497-8e6a-39122c818c49)

**Comment by GirafiStudios** [comment]
I'm unable to reproduce this unfortunately. Could be a problem with the modpack you're playing only.

Is the blocks just gone, or are they invisible?
