### ISSUE TITLE
Magenta crystal glass is not transparent

### ISSUE THREAD

**Issue by GoldenTotem** [TeamMetallurgy/Atum2#424]
Minecraft 1.16.5  Atum 2.2.12

atum:magenta_stained_palm_framed_crystal_glass  and   atum:magenta_stained_deadwood_framed_crystal_glass  is not transparent.
![2024-03-28_18 04 52](https://github.com/TeamMetallurgy/Atum2/assets/70516358/e52704f4-d523-4be1-8319-2a0cbfcf2520)

**Comment by GirafiStudios** [comment]
Can't fix. See reason here https://github.com/TeamMetallurgy/Atum2/issues/419
