### ISSUE TITLE
Wrong max stack size of item

### ISSUE THREAD

**Issue by GoldenTotem** [TeamMetallurgy/Atum2#425]
Minecraft 1.16.5  Atum 2.2.12

The max stack size of item Ra's step, Nepthys's Guard and Nebu hammer is 64. They should be 1.

**Comment by GirafiStudios** [comment]
Good catch, you're indeed right! Will be fixed for the future

See why it can't be fixed for 1.16.5 here https://github.com/TeamMetallurgy/Atum2/issues/419
