### ISSUE TITLE
Nepthys guard cannot reduce undead mobs' projectile damage

### ISSUE THREAD

**Issue by GoldenTotem** [TeamMetallurgy/Atum2#427]
Minecraft 1.16.5  Atum 2.2.12

Nepthys guard can only reduce normal attack damage, but damage from projectile like skeleton's arrow and drowned's trident will be ignored.

**Comment by GirafiStudios** [comment]
Will be looked at for the future, thanks!

See why it can't be fixed for 1.16.5 here https://github.com/TeamMetallurgy/Atum2/issues/419
