### ISSUE TITLE
Wrong harvest level of Block of Nebu

### ISSUE THREAD

**Issue by GoldenTotem** [TeamMetallurgy/Atum2#429]
Minecraft 1.16.5  Atum 2.2.12

The harvest of nebu ore is 2(need iron pickaxe or higher to break), but nebu block is 0. It should be the same as ore.

**Comment by GirafiStudios** [comment]
Will be looked at for the future, thanks!

See why it can't be fixed for 1.16.5 here https://github.com/TeamMetallurgy/Atum2/issues/419
