### ISSUE TITLE
CF page still shows lighthouse

### ISSUE THREAD

**Issue by Omega58** [TeamMetallurgy/Atum2#433]
Not really an issue, but I keep seeing the curseforge page having a screenshot of the lighthouse structure, which was removed over 3 years ago alongside sunspeakers and other stuff related to it.

So unless it is kept for a reason, or it will be re-added, I honestly don't know why is it still there.

**Comment by GirafiStudios** [comment]
Good point, screenshot of the lighthouse removed now :)
