### ISSUE TITLE
Leaves decay in creative.

### ISSUE THREAD

**Issue by darkhax** [TeamMetallurgy/Atum2#48]
In vanilla, placing leave blocks will set them as non-decayable. This means that you can build structures using the leaf block and not have to include wood blocks, or be limited by the rules for leaf decay. The atum palm leaves do not follow this rule. 

Vanilla Birch Leaves
![image](https://user-images.githubusercontent.com/2250798/40582957-1760c4aa-6141-11e8-8173-e50ef6b0a8a3.png)

Atum Palm Leaves
![image](https://user-images.githubusercontent.com/2250798/40582959-217183e4-6141-11e8-9ada-f26f21286010.png)

**Comment by GirafiStudios** [comment]
It should behave like that when placed, not just in creative. But good catch ^^
