### ISSUE TITLE
Death returns to spawn

### ISSUE THREAD

**Issue by Ceifeire** [TeamMetallurgy/Atum2#54]
So not entirelly sure if this is supposed to happen but in my world when I die i respawn in the Autm dimension at the coordinates for spawn in the overworld. In my case though this is really bad becasue my hosue is 8000 blocks from spawn so I ahve to trek 8000 blocks in the atum to get back to my portal to leacve the atum. If there is a way to change that i would really like to know how. Thank you

**Comment by GirafiStudios** [comment]
Is this for Atum or Atum 2?

**Comment by Ceifeire** [comment]
atum 1.7.10-.0.6.77

**Comment by GirafiStudios** [comment]
This is the repository for Atum 2, so wrong place to report it first of all :)
Atum for 1.7.10 haven't been supported for years, so I think you unfortunately is out of luck.
