### ISSUE TITLE
Spawnpoint in atum uses overworld coordinates

### ISSUE THREAD

**Issue by revanace** [TeamMetallurgy/Atum2#55]
Version: Atum2-1.12.2-2.0.0.alpha157

Overworld spawn (after death):  -122/64/192
Atum spawn (after death): -131/69/202

Portal coordinates (in atum):  -509/64/67
Portal coordinates (in overworld):  -512/64/64

As you can see it spawns me back to the overworld spawn coordinates, not near the nearest or latest used portal or whatever logic you want to use.

**Comment by GirafiStudios** [comment]
Not an issue. Meant to be this way. No distance "cheating" for portals like the nether.
