### ISSUE TITLE
[Feature Request] Dynamic Trees

### ISSUE THREAD

**Issue by naqaden** [TeamMetallurgy/Atum2#61]
In short, please consider becoming a member of [this list](https://www.curseforge.com/minecraft/mc-mods/dynamictrees/relations/dependents?filter-related-dependents=3).

If done, Atum trees would be more organic in appearance and growth, and more realistic to fell, all optionally via a separate add-on mod.

**Comment by GirafiStudios** [comment]
Thanks for your suggestion!
I don't really see any documentation on this anywhere, is there any?
If it's not something that's pretty easy to do, I mostly likely won't do it.

**Comment by naqaden** [comment]
Thanks for considering :] This looks like the closest answer: [ExampleTrees](https://github.com/ferreusveritas/ExampleTrees) (from [this reply](https://minecraft.curseforge.com/projects/dynamictrees?page=3#c782))

**Comment by aycfes** [comment]
ik how late i am, but i agree DT is one of my favorite mods

**Comment by GirafiStudios** [comment]
I'm not personally gonna use time on this. But if somebody make a pull request for it, that would be much appreciated :)

**Comment by Weissmoon** [comment]
I would like to do this, but I cannot do it easily due to both projects using different mappings.

**Comment by GirafiStudios** [comment]
@Weissmoon that would be much appreciated :) I'll look into a workaround for the different mappings

**Comment by GirafiStudios** [comment]
@Weissmoon I think I have a workaround. Could you contact me on Discord at some point, when you have time? :)
Server invite link: https://discordapp.com/invite/TuJXw7V

**Comment by GirafiStudios** [comment]
In case anybody wanna looks into this. Rustic have quite a good example here: https://github.com/the-realest-stu/Rustic/tree/master/src/main/java/rustic/compat/dynamictrees

**Comment by Azuriuz** [comment]
I can do nothing to really help, but I agree dynamic Atum trees would be awesome! BoP has an addon that adds palm trees to dynamic trees, if anyone wants an easy reference to base off of. 

https://media.forgecdn.net/attachments/thumbnails/225/581/310/172/oasis.png <---example

**Comment by XvBUSHvX** [comment]
I came to this issue tracker having an intending to make this suggestion myself. As it already exists I have followed this thread in hopes to learn of anyone willing and capable to take on this task, and hope to express my appreciation, in advance, to anyone who does so.

**Comment by GirafiStudios** [comment]
Looks like Atum support have been fully added now, as of an hour ago
https://github.com/supermassimo/DynamicTrees-ExC/commit/a9212c95a22a165101135bd7c836f3da5c0968a1
So it'll probably be available for download soon!
