### ISSUE TITLE
Mod crashes upon loading up

### ISSUE THREAD

**Issue by Feathered-Velociraptor** [TeamMetallurgy/Atum2#70]
[atum2_crash_report.txt](https://github.com/TeamMetallurgy/Atum2/files/2989997/atum2_crash_report.txt)

**Comment by GirafiStudios** [comment]
Thank you for your report!
One of the other mods you're using is adding an item or block with an invalid registry name. I can make a workaround on our end though.
Would you happen to use the Twitch Launcher? If so, can I get you to send me the pack?

**Comment by Feathered-Velociraptor** [comment]
Could you possibly link twitch launcher/ where you download it, this is the first crash report I have submitted, sorry.

**Comment by GirafiStudios** [comment]
It was just if you used it, it's totally fine if you don't :)
Could I get you to try the build from here: http://girafi.dk/jenkins/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%20Jenkins/4/ , and see if that fixes it for you?
Please let me know when you have tried it.

**Comment by Feathered-Velociraptor** [comment]
thanks

**Comment by GirafiStudios** [comment]
@Feathered-Velociraptor any luck?

**Comment by Feathered-Velociraptor** [comment]
Seems to be working

**Comment by GirafiStudios** [comment]
Glad it worked.
Appreciate you trying it out!
