### ISSUE TITLE
sunspeakers are bugged²

### ISSUE THREAD

**Issue by aycfes** [TeamMetallurgy/Atum2#72]
they SEVERELY overspawn, like, hundreds at a single beacon structure
also, when one of them got hit by an archer, they killed it and then aggroed on me, as if i had hit them.

**Comment by GirafiStudios** [comment]
Thanks for your report!
Could you provide screenshots, and ways to reproduce the overspawn issue?
The aggro issue is a known issue.

**Comment by aycfes** [comment]
o have no clue on how to reproduce it, but here are the screenshots (note that i've already killed a lot of them)

(also, nice temple, man)
![2019-03-22_12 26 50](https://user-images.githubusercontent.com/38796165/54833931-d34b1380-4c9d-11e9-92f7-4f38989808c0.png)
![2019-03-22_12 25 48](https://user-images.githubusercontent.com/38796165/54833932-d34b1380-4c9d-11e9-8a28-6095d626edaa.png)
![2019-03-22_12 26 02](https://user-images.githubusercontent.com/38796165/54833933-d3e3aa00-4c9d-11e9-9365-0469cde89ee8.png)

**Comment by GirafiStudios** [comment]
I was able to reproduce it after a while. I will look into it :)
