### ISSUE TITLE
[Compat] Atum Biomes in Overworld via Climatic Biomes

### ISSUE THREAD

**Issue by CREEATION** [TeamMetallurgy/Atum2#74]
I'm trying to integrate Atum into the overworld by very rarely generating an Oasis in deserts, which works for the most part.

However, instead of sand I'm getting stone blocks generated:

![2019-03-25_07 50 07](https://user-images.githubusercontent.com/3277769/54900380-45586e00-4ed3-11e9-8712-075d5bb26b03.png)
![2019-03-25_07 52 22](https://user-images.githubusercontent.com/3277769/54900382-45586e00-4ed3-11e9-9e23-2102c99eeb33.png)

This happens with the others, like Sand Planes, too. I hope this can somehow be fixed, because I'm planning to spawn partial portal frame structures in the overworld to introduce players to Atum 🐢

**Comment by GirafiStudios** [comment]
Thanks for your report!
Could I get you to send your Climatic Biomes config?

**Comment by CREEATION** [comment]
Sure, but I've updated the values since opening the issue (and probably need to tweak more in the future):
```
biome(minecraft:desert)
biome(minecraft:desert)
biome(minecraft:desert)
biome(minecraft:desert)
biome(minecraft:desert)
biome(minecraft:desert)
seed(minecraft:desert, 250, atum:dead_oasis)
seed(minecraft:desert, 1000, atum:oasis)
biome(minecraft:desert_hills)
biome(minecraft:desert_hills)
biome(minecraft:desert_hills)
biome(minecraft:mutated_desert)
noise(minecraft:mesa, 5, minecraft:mesa_clear_rock)
noise(minecraft:mesa, 5, minecraft:mesa_clear_rock)
noise(minecraft:mesa, 5, minecraft:mesa_rock)
noise(minecraft:mesa, 5, minecraft:mesa_rock)
noise(minecraft:mesa, 5, minecraft:mutated_mesa_rock)
noise(minecraft:mutated_mesa_clear_rock, 5, minecraft:mutated_mesa)
```

**Comment by GirafiStudios** [comment]
Cheers.
I hopefully have time to take a look at this later. Quite busy today.

**Comment by GirafiStudios** [comment]
Made a workaround for it. Since it's a very minor thing I'm not gonna release a new version for just that.
But you can go grab the fix from Jenkins here: http://girafi.dk/jenkins/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%20Jenkins/8/

**Comment by CREEATION** [comment]
Hey, awesome! Thanks for the quick fix. 💃
