### ISSUE TITLE
Sand layers don't stack when placed

### ISSUE THREAD

**Issue by CREEATION** [TeamMetallurgy/Atum2#79]
Hello again ,o/

Sand layers don't stack when manually placed in creative, like snow does. That's pretty much it. 🐢 
Not sure if they're supposed to stack, though.

![2019-03-29_12 25 24](https://user-images.githubusercontent.com/3277769/55229593-c1c5b680-521d-11e9-9328-66a2b0f7220b.png)

I'm trying to fill up the portal structure hole.

**Comment by GirafiStudios** [comment]
What Forge version are you using?

**Comment by GirafiStudios** [comment]
There may be some issues with block placing in some newer version of Forge, but they should work in the latest version of Forge. At least it works for me.

![qpN66uS](https://user-images.githubusercontent.com/6305377/55233244-44537380-5228-11e9-8082-38d4459ddbd0.png)

**Comment by CREEATION** [comment]
Yeah, that must be it. I'm using `14.23.5.2823` currently for testing, but I'll downgrade eventually. Thanks 🐢

**Comment by GirafiStudios** [comment]
It might be broken there, but should work in 2824 :)
