### ISSUE TITLE
Armor Set Renders

### ISSUE THREAD

**Issue by GirafiStudios** [TeamMetallurgy/Atum2#83]
The following armor sets needs 3D renders:
- [x] Ra
- [x] Atem

**Comment by ArcanHage** [comment]
This mod really needs appropriate renders for it's armors, personally I think I'm not the best artist this mod deserves, but I can try. ( ~ playing with it on a personal modpack and loving! ~ ) It would be awesome if you (Darkhax and GirafiStudios) could tell me how exactly do you want the models to look like (matching the art style obviously). 

Here are some pic of my ~amateur~ models I've made some time ago:
The techy armor I made using Extra Bit Manipulation (So I can't export to java)

![manoculum_pedestal](https://user-images.githubusercontent.com/22179892/60861419-cfadaf00-a1f0-11e9-892c-b910a06dfc56.png)
![steelpaper_blade](https://user-images.githubusercontent.com/22179892/60861420-cfadaf00-a1f0-11e9-94fc-bab406fdc036.png)
![Sword](https://user-images.githubusercontent.com/22179892/60861421-cfadaf00-a1f0-11e9-8ff6-cc00bf31a138.png)
![TechyArmor](https://user-images.githubusercontent.com/22179892/60861422-cfadaf00-a1f0-11e9-9e89-7ed2445cb85e.png)
![Dexter](https://user-images.githubusercontent.com/22179892/60861423-d0464580-a1f0-11e9-9ed0-a415674d4dc9.png)
![MagicHood](https://user-images.githubusercontent.com/22179892/60861424-d0464580-a1f0-11e9-843a-808f1915dc31.png)
![MagicHood1](https://user-images.githubusercontent.com/22179892/60861425-d0464580-a1f0-11e9-8117-7cbb2962d301.png)

**Comment by ArcanHage** [comment]
(Update)
I've made the Atum armor:
![AtumArmor](https://user-images.githubusercontent.com/22179892/61262924-7d730d80-a75d-11e9-8665-00889d899e53.png)

[texture_and_java.zip](https://github.com/TeamMetallurgy/Atum2/files/3395063/texture_and_java.zip)
