### ISSUE TITLE
[Suggestion] [Tough As Nails] [Compatability] Finish the compatability?

### ISSUE THREAD

**Issue by Carvercarver1** [TeamMetallurgy/Atum2#88]
Yes, it does have it by default - player slowly heating up on the sun/surface, and cools down underground and during night. (How hot is the Atum's desert, actually? Maybe needs to increase heating rates... by a lot)

But, unfortunately, Atum's clothes does not provide you with heat resistance/immunity like TaN's jelly armor from the TaN itself. Any way to add compat? I'm pretty sure you can, concidering that you slammed TC aspects into the mod.

**Comment by GirafiStudios** [comment]
Closing, since armor can be added in the TaN config. According to what @Carvercarver1 said on Discord
