### ISSUE TITLE
Crash with IC2 beta when right clicking one of their new pipes

### ISSUE THREAD

**Issue by LumberWizard** [TeamMetallurgy/Atum2#92]
Crashlog: https://pastebin.com/gUDJAjPK

Steps to reproduce:
1. Place down a fluid pipe from IC2
2. Right click the pipe

Forge version: 14.23.5.2386
IC2 version: 2.8.144
Atum version: 2.0.5

**Comment by GirafiStudios** [comment]
This is a problem with how IC2 is handling the "hasCapability" in their Fluid Pipe tile entity.
The place that is mentioned in the crash log on Atum's side is literally just a call to Forge code, so I can unfortunately not do anything on my side. Your best bet would be to report it to IC2 :)

**Comment by LumberWizard** [comment]
But IC2's issue tracker requires I open an account there :(

That's actually the sole reason I went here first

**Comment by GirafiStudios** [comment]
I can't do anything, I would if I could. I'm just calling a method in Forge, and it's crashing before I'm even doing anything with it.
If IC2 was open source I could tell you exactly what's going, but unfortunately it's not.
